/* Authored teaching simulations. No model calls, tracking, or learner uploads. */
(function(root){
  'use strict';
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const scenes={
    '1':{title:['From information to an answer','Տեղեկությունից մինչև պատասխան'],steps:[
      [['Your input','Ձեր մուտքը'],['The shop closes at 18:00. Write a customer notice.','Խանութը փակվում է 18:00-ին։ Գրիր հաղորդագրություն գնորդին։'],['Source','Աղբյուր']],
      [['Context','Համատեքստ'],['Instruction + supplied fact. No address or opening time was given.','Հրահանգ և տրված փաստ։ Հասցե կամ բացվելու ժամ չի տրվել։'],['Source + request','Աղբյուր և հարցում']],
      [['Generation','Ստեղծում'],['“Our shop closes at 18:00.” The draft is generated piece by piece.','«Մեր խանութը փակվում է 18:00-ին»։ Նախագիծը ստեղծվում է մաս առ մաս։'],['Our | shop | closes | at | 18:00','Մեր | խանութը | փակվում է | 18:00-ին']],
      [['Human check','Մարդու ստուգում'],['The closing time matches. Any invented address must be removed.','Փակվելու ժամը համապատասխանում է։ Հորինված հասցեն պետք է հեռացնել։'],['Supported: 18:00','Հաստատված՝ 18:00']]]},
    '2':{title:['Build a brief that can be checked','Կազմեք ստուգելի առաջադրանք'],steps:[
      [['A vague request','Անորոշ հարցում'],['“Plan my study week.” The assistant does not know your time limits.','«Պլանավորիր ուսումնական շաբաթս»։ Օգնականը չգիտի ժամանակային սահմանները։'],['Task: study plan','Խնդիր՝ ուսումնական պլան']],
      [['Add the evidence','Ավելացրեք տվյալները'],['Tuesday: 30 minutes. Thursday: 45. Saturday: 60.','Երեքշաբթի՝ 30 րոպե, հինգշաբթի՝ 45, շաբաթ՝ 60։'],['30 + 45 + 60 = 135 min','30 + 45 + 60 = 135 րոպե']],
      [['Define success','Սահմանեք հաջողությունը'],['Cover prompting and source checking without exceeding any daily limit.','Ներառել հրահանգներն ու աղբյուրների ստուգումը՝ չանցնելով օրական սահմանը։'],['Two topics · three sessions','Երկու թեմա · երեք հանդիպում']],
      [['Inspect the result','Ստուգեք արդյունքը'],['Tue: prompting 30. Thu: source checks 45. Sat: mixed practice 60. Verify totals yourself.','Երք․՝ հրահանգներ 30, հնգ․՝ աղբյուրներ 45, շբթ․՝ համակցված փորձ 60։ Ստուգեք գումարը։'],['135 / 135 min','135 / 135 րոպե']]]},
    '3':{title:['Trace a claim to its evidence','Պնդումից հասեք ապացույցին'],steps:[
      [['The claim','Պնդումը'],['“The library is open every Sunday.” A polished sentence is not a source.','«Գրադարանը բաց է ամեն կիրակի»։ Սահուն նախադասությունը աղբյուր չէ։'],['Every Sunday?','Ամեն կիրակի՞']],
      [['The source','Աղբյուրը'],['Fictional notice: “Exam-period opening: Sunday 10:00-14:00.”','Հորինված ծանուցում՝ «Քննաշրջանում՝ կիրակի 10:00-14:00»։'],['Condition: exam period','Պայման՝ քննաշրջան']],
      [['The missing condition','Կորած պայմանը'],['The notice supports an exam-period schedule, not a year-round promise.','Ծանուցումը հաստատում է քննաշրջանի ժամերը, ոչ ամբողջ տարվա խոստումը։'],['Every Sunday ≠ exam Sundays','Ամեն կիրակի ≠ քննաշրջանի կիրակիներ']],
      [['The corrected claim','Ուղղված պնդումը'],['“During the exam period, Sunday opening is 10:00-14:00, according to the notice.”','«Ըստ ծանուցման՝ քննաշրջանում կիրակի օրերին բաց է 10:00-14:00»։'],['Condition restored','Պայմանը վերականգնված է']]]},
    '4':{title:['From notes to a useful table','Նշումներից դեպի օգտակար աղյուսակ'],steps:[
      [['Read','Կարդացեք'],['Ani drafts the agenda by Tuesday. Aram checks the room; no deadline given.','Անին օրակարգը կազմում է մինչև երեքշաբթի։ Արամը ստուգում է սենյակը․ ժամկետ չկա։'],['Two actions','Երկու գործողություն']],
      [['Extract','Առանձնացրեք'],['Keep owner, action, and deadline as separate fields.','Պատասխանատուն, գործողությունն ու ժամկետը պահեք առանձին դաշտերում։'],['Owner | Action | Deadline','Պատասխանատու | Գործ | Ժամկետ']],
      [['Mark the gap','Նշեք բացը'],['Do not assign Tuesday to Aram simply because it appeared nearby.','Արամի ժամկետը մի դարձրեք երեքշաբթի՝ միայն որովհետև այդ օրը կողքին էր։'],['Aram: deadline not stated','Արամ՝ ժամկետը նշված չէ']],
      [['Review','Վերանայեք'],['Confirm Ani’s deadline. Ask Aram for his deadline before scheduling reminders.','Հաստատեք Անիի ժամկետը։ Հիշեցում կազմելուց առաջ հարցրեք Արամի ժամկետը։'],['Preserve facts · expose gaps','Պահպանել փաստերը · ցույց տալ բացերը']]]},
    '5':{title:['A tool must pass the requirements first','Գործիքը նախ պետք է բավարարի պահանջներին'],steps:[
      [['Define the job','Սահմանեք խնդիրը'],['Draft an Armenian summary from an approved internal document.','Հաստատված ներքին փաստաթղթից կազմել հայերեն ամփոփում։'],['Language + source fidelity','Լեզու և աղբյուրին հավատարմություն']],
      [['Check access','Ստուգեք հասանելիությունը'],['Does this account support the file type and the required data policy?','Այս հաշիվն աջակցո՞ւմ է ֆայլի տեսակին և տվյալների պահանջվող քաղաքականությանը։'],['Required: permitted data use','Պարտադիր՝ տվյալների թույլատրված օգտագործում']],
      [['Compare outputs','Համեմատեք արդյունքները'],['A preserves all conditions. B is prettier but uploads data to an unapproved service.','Ա-ն պահպանում է պայմանները։ Բ-ն գեղեցիկ է, բայց տվյալները փոխանցում է չթույլատրված ծառայությանը։'],['A: eligible | B: blocked','Ա՝ ընդունելի | Բ՝ արգելափակված']],
      [['Record a decision','Գրանցեք որոշումը'],['Choose only among eligible options. Record the test, account type, owner, and review date.','Ընտրեք միայն պահանջներն անցած տարբերակներից։ Գրանցեք փորձը, հաշվի տեսակը, պատասխանատուին և վերանայման օրը։'],['A shortlist, not a permanent winner','Կարճ ցանկ, ոչ հավերժ հաղթող']]]},
    '6':{title:['Approval belongs to an exact version','Հաստատումը վերաբերում է կոնկրետ տարբերակին'],steps:[
      [['Draft v1','Նախագիծ՝ տարբ․ 1'],['The system prepares a message. It has no permission to send it.','Համակարգը պատրաստում է հաղորդագրություն։ Ուղարկելու թույլտվություն չունի։'],['Awaiting review','Սպասում է ստուգման']],
      [['Review v1','Ստուգել տարբ․ 1-ը'],['A coordinator checks the facts and the intended recipient, then approves v1.','Համակարգողը ստուգում է փաստերն ու հասցեատիրոջը և հաստատում 1-ին տարբերակը։'],['v1 approved','Տարբ․ 1-ը հաստատված է']],
      [['Edit → v2','Փոփոխում → տարբ․ 2'],['The fee changes. The earlier approval no longer covers this draft.','Վճարը փոխվում է։ Նախորդ հաստատումն այլևս չի վերաբերում այս նախագծին։'],['Approval invalidated','Հաստատումն անվավեր է']],
      [['Review again','Կրկին ստուգել'],['The new version waits. Automation must not reuse v1 approval to send v2.','Նոր տարբերակը սպասում է։ Ավտոմատացումը չի կարող հին հաստատմամբ ուղարկել նոր տարբերակը։'],['Stop until v2 is approved','Կանգ՝ մինչև տարբ․ 2-ի հաստատումը']]]},
    '7':{title:['Fewer tokens, but what about the result?','Քիչ թոքեններ, բայց ի՞նչ արդյունք'],steps:[
      [['Full context','Ամբողջ համատեքստ'],['Teaching example: 4,000 input tokens + 300 output tokens.','Ուսումնական օրինակ՝ 4,000 մուտքային և 300 ելքային թոքեն։'],['4,000 input','4,000 մուտքային']],
      [['Relevant excerpt','Առնչվող հատված'],['Keep the governing facts and exceptions: 1,000 input tokens + 300 output tokens.','Պահեք գերակա փաստերն ու բացառությունները՝ 1,000 մուտքային և 300 ելքային թոքեն։'],['1,000 input','1,000 մուտքային']],
      [['Calculate','Հաշվեք'],['At hypothetical rates of $2/M input and $8/M output: $0.0104 becomes $0.0044 per attempt.','Պայմանական $2/մլն մուտք և $8/մլն ելք գներով՝ $0.0104-ը դառնում է $0.0044 մեկ փորձի համար։'],['75% less input ≠ 75% less total cost','75% քիչ մուտք ≠ 75% քիչ ընդհանուր ծախս']],
      [['Check quality','Ստուգեք որակը'],['If the excerpt drops a condition or adds correction time, reject or revise it. Compare accepted results.','Եթե հատվածը կորցնում է պայման կամ ավելացնում ուղղման ժամանակը, մերժեք կամ վերանայեք։ Համեմատեք ընդունված արդյունքները։'],['Quality first, then cost','Նախ որակ, հետո ծախս']]]},
    '8':{title:['A registration chart that tells the truth','Գրանցումների ճշգրիտ պատկեր'],steps:[
      [['Count all rows','Հաշվել բոլոր տողերը'],['Eight records do not mean eight confirmed attendees.','Ութ գրառում չի նշանակում ութ հաստատված մասնակից։'],['8 records','8 գրառում']],
      [['Separate statuses','Տարբերակել կարգավիճակները'],['Five confirmed, two pending, one cancelled.','Հինգ հաստատված, երկու սպասող, մեկ չեղարկված։'],['5 + 2 + 1 = 8','5 + 2 + 1 = 8']],
      [['Choose the denominator','Ընտրել հայտարարը'],['With capacity 20, confirmed occupancy is 5/20 = 25%.','20 տեղից հաստատվածները 5-ն են․ զբաղվածությունը՝ 5/20 = 25%։'],['5 / 20 = 25%','5 / 20 = 25%']],
      [['Show the result','Ցույց տալ արդյունքը'],['Label confirmed and pending separately. Do not imply pending requests are approved.','Հաստատվածն ու սպասողը նշեք առանձին։ Սպասող հայտը մի ներկայացրեք որպես հաստատված։'],['5 confirmed · 2 pending','5 հաստատված · 2 սպասող']]]}
  };
  // Visual marks repeat the adjacent text; hide them from assistive technology.
  function diagram(id,n,lang){
    const hy=lang==='hy',pick=(en,am)=>hy?am:en;
    const tile=(label,value,active=true)=>`<div class="diagram-tile${active?' is-lit':''}"><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`;
    let body='';
    if(id==='1')body=`<div class="diagram-flow">${tile(pick('Supplied fact','Տրված փաստ'),'18:00',n>=0)}<span>→</span>${tile(pick('Draft','Նախագիծ'),n>=2?'18:00':'…',n>=2)}<span>→</span>${tile(pick('Check','Ստուգում'),n>=3?'✓':'?',n>=3)}</div><p>${pick('A simplified flow, not an exact tokenizer or a view inside a model.','Պարզեցված հոսք է, ոչ ճշգրիտ թոքենացում կամ մոդելի ներքին տեսք։')}</p>`;
    if(id==='2')body=`<div class="diagram-stack">${tile(pick('Tuesday','Երեքշաբթի'),n>=1?pick('30 min','30 րոպե'):'?')}${tile(pick('Thursday','Հինգշաբթի'),n>=1?pick('45 min','45 րոպե'):'?')}${tile(pick('Saturday','Շաբաթ'),n>=1?pick('60 min','60 րոպե'):'?')}</div><div class="diagram-band">${n>=2?pick('Prompting + source checks','Հրահանգներ + աղբյուրների ստուգում'):pick('Missing constraints','Սահմանները բացակայում են')}</div>`;
    if(id==='3')body=`<div class="diagram-stack">${tile(pick('Draft scope','Նախագծի ծավալ'),n>=3?pick('Exam period','Քննաշրջան'):pick('Every Sunday','Ամեն կիրակի'))}${tile(pick('Source scope','Աղբյուրի ծավալ'),n>=1?pick('Exam period','Քննաշրջան'):'?',n>=1)}</div><div class="diagram-band">${n>=3?'✓':n>=2?'≠':'?'} ${pick('Does the scope match?','Ծավալը համապատասխանո՞ւմ է։')}</div>`;
    if(id==='4')body=`<div class="diagram-table"><div><b>${pick('Owner','Պատասխանատու')}</b><b>${pick('Deadline','Ժամկետ')}</b></div><div><span>${pick('Ani','Անի')}</span><strong>${n>=1?pick('Tuesday','Երեքշաբթի'):'…'}</strong></div><div><span>${pick('Aram','Արամ')}</span><strong>${n>=2?pick('Not stated','Նշված չէ'):'…'}</strong></div></div>`;
    if(id==='5')body=`<div class="diagram-stack">${tile(pick('Tool A','Գործիք Ա'),n>=2?pick('✓ Eligible','✓ Ընդունելի'):'?')}${tile(pick('Tool B','Գործիք Բ'),n>=2?pick('× Blocked','× Արգելափակված'):'?',n<2)}</div><div class="diagram-band">${pick('Data permission is a gate, not bonus points.','Տվյալների թույլտվությունը պարտադիր պայման է, ոչ հավելյալ միավոր։')}</div>`;
    if(id==='6')body=`<div class="diagram-flow">${tile(pick('Document','Փաստաթուղթ'),n<2?'v1':'v2')}<span>→</span>${tile(pick('Approval','Հաստատում'),n===1?'✓':pick('Waiting','Սպասում է'),n===1)}<span>→</span>${tile(pick('Send','Ուղարկել'),pick('On hold','Կասեցված'),false)}</div>`;
    if(id==='7')body=`<div class="diagram-cost"><div><span>${pick('Full input','Լրիվ մուտք')}</span><i style="width:100%"></i><b>4,000</b></div><div><span>${pick('Relevant input','Առնչվող մուտք')}</span><i style="width:${n>=1?25:100}%"></i><b>${n>=1?'1,000':'4,000'}</b></div></div><div class="diagram-band">${n>=2?'$0.0104 → $0.0044':pick('Compare input tokens','Համեմատեք մուտքային թոքենները')}</div>`;
    if(id==='8')body=`<div class="diagram-seats">${Array.from({length:20},(_,i)=>`<i class="${n===0?(i<8?'seat-unknown':''):(i<5?'seat-confirmed':i<7?'seat-pending':'')}"></i>`).join('')}</div><div class="diagram-band">${n===0?pick('8 records; status not yet checked','8 գրառում․ կարգավիճակը դեռ չի ստուգվել'):pick('5 confirmed · 2 pending · capacity 20','5 հաստատված · 2 սպասող · 20 տեղ')}</div>`;
    return `<div class="visual-diagram" aria-hidden="true">${body}</div>`;
  }
  function render(chapter,lang){
    const s=scenes[chapter]; if(!s)return '';
    const i=lang==='hy'?1:0;
    return `<section class="teaching-visual" data-teaching-visual="${chapter}" data-lang="${lang}" data-step="0"><div class="visual-heading"><span>${i?'ՏԵՍԵՔ՝ ԻՆՉՊԵՍ Է ԱՇԽԱՏՈՒՄ':'SEE HOW IT WORKS'}</span><h2>${esc(s.title[i])}</h2><p>${i?'Նախապես գրված ուսումնական պատկերում է, ոչ իրական ԱԲ պատասխան։ Քայլերն ուսումնասիրեք ձեր տեմպով։':'An authored teaching simulation, not a live AI response. Explore each step at your own pace.'}</p></div><div class="visual-stages" role="group" aria-label="${esc(s.title[i])}">${s.steps.map((v,n)=>`<button type="button" data-visual-step="${n}" aria-pressed="${n===0}"><span>${n+1}</span>${esc(v[0][i])}</button>`).join('')}</div><div class="visual-frame"><div data-visual-diagram>${diagram(chapter,0,lang)}</div><div class="visual-artifact" data-visual-artifact>${esc(s.steps[0][2][i])}</div><p data-visual-explanation>${esc(s.steps[0][1][i])}</p><div class="visual-meter" aria-hidden="true"><i style="width:25%"></i></div></div><div class="visual-controls"><button type="button" data-visual-play>${i?'Դիտել քայլերը':'Play walkthrough'}</button><button type="button" data-visual-next>${i?'Հաջորդ քայլը':'Next step'}</button><button type="button" data-visual-reset>${i?'Սկսել սկզբից':'Restart'}</button><span data-visual-status role="status">1 / 4</span></div><details class="visual-transcript"><summary>${i?'Կարդալ բոլոր քայլերը':'Read all steps'}</summary><ol>${s.steps.map(v=>`<li><strong>${esc(v[0][i])}.</strong> ${esc(v[1][i])}</li>`).join('')}</ol></details></section>`;
  }
  let timer=null,active=null;
  function stop(){if(timer)root.clearInterval(timer);timer=null;if(active){const p=active.querySelector('[data-visual-play]');if(p)p.textContent=active.dataset.lang==='hy'?'Դիտել քայլերը':'Play walkthrough';}active=null;}
  function show(el,n){const s=scenes[el.dataset.teachingVisual],i=el.dataset.lang==='hy'?1:0;el.dataset.step=String(n);el.querySelectorAll('[data-visual-step]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.visualStep)===n)));el.querySelector('[data-visual-artifact]').textContent=s.steps[n][2][i];el.querySelector('[data-visual-explanation]').textContent=s.steps[n][1][i];el.querySelector('[data-visual-diagram]').innerHTML=diagram(el.dataset.teachingVisual,n,el.dataset.lang);el.querySelector('.visual-meter i').style.width=`${(n+1)*25}%`;el.querySelector('[data-visual-status]').textContent=`${n+1} / 4`;}
  function bind(){document.addEventListener('click',e=>{const el=e.target.closest('[data-teaching-visual]');if(!el)return;const b=e.target.closest('button');if(!b)return;
    if(b.hasAttribute('data-visual-step')){stop();show(el,Number(b.dataset.visualStep));}
    if(b.hasAttribute('data-visual-reset')){stop();show(el,0);}
    if(b.hasAttribute('data-visual-next')){stop();show(el,(Number(el.dataset.step)+1)%4);}
    if(b.hasAttribute('data-visual-play')){if(timer){stop();return;}if(root.matchMedia?.('(prefers-reduced-motion: reduce)').matches){show(el,(Number(el.dataset.step)+1)%4);return;}active=el;if(Number(el.dataset.step)===3)show(el,0);b.textContent=el.dataset.lang==='hy'?'Դադարեցնել':'Pause';timer=root.setInterval(()=>{if(!el.isConnected){stop();return;}const n=Number(el.dataset.step);if(n===3){stop();return;}show(el,n+1);},2400);}
  });document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});}
  const api={render,bind,stop,scenes};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.EuaTeachingVisuals=api;
})(typeof window!=='undefined'?window:globalThis);
