(function (root, factory) {
  "use strict";
  const catalog = factory();
  if (typeof module === "object" && module.exports) module.exports = catalog;
  else root.EuaCourseCatalog = catalog;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const lesson = (id, sort, title_en, title_hy, objective_en, objective_hy, points_en, points_hy, practice_en, practice_hy, takeaway_en, takeaway_hy) => ({
    id, sort_order: sort, title_en, title_hy, objective_en, objective_hy,
    points_en, points_hy, practice_en, practice_hy, takeaway_en, takeaway_hy
  });

  const modules = [
    {
      id: 101, sort_order: 1,
      title_en: "Start Here: AI, You, and Human Judgment",
      title_hy: "Սկիզբ. ԱԲ-ը, դուք և մարդկային դատողությունը",
      quiz_focus_en: "Which practice best reflects a human-led approach to AI?",
      quiz_focus_hy: "Ո՞ր գործելակերպն է լավագույնս արտահայտում ԱԲ-ի մարդակենտրոն կիրառությունը։",
      quiz_options_en: ["Delegate the task, check the result, and own the decision", "Accept every answer", "Upload private data for context", "Let the tool make final decisions"],
      quiz_options_hy: ["Փոխանցել առաջադրանքը, ստուգել արդյունքը և պատասխանատու լինել որոշման համար", "Ընդունել յուրաքանչյուր պատասխան", "Համատեքստի համար բեռնել գաղտնի տվյալներ", "Վերջնական որոշումը թողնել գործիքին"],
      quiz_correct: 0,
      lessons: [
        lesson(101, 1, "Welcome to AI Explorers", "Բարի գալուստ «ԱԲ բացահայտողներ»", "Understand the course journey and what successful participation looks like.", "Հասկացեք դասընթացի ուղին և հաջող մասնակցության չափանիշները։", ["Learn through short explanations, experiments, and reflection", "Create a practical output in every module", "Finish with an original, tested capstone"], ["Սովորել կարճ բացատրություններով, փորձերով և վերլուծությամբ", "Յուրաքանչյուր մոդուլում ստեղծել գործնական արդյունք", "Ավարտել ինքնուրույն և փորձարկված նախագծով"], "Write one AI skill you want to build and one real problem you want to solve.", "Գրեք մեկ ԱԲ հմտություն, որը ցանկանում եք զարգացնել, և մեկ իրական խնդիր, որը ցանկանում եք լուծել։", "Progress means making better decisions with AI, not collecting tool names.", "Առաջընթացը ԱԲ-ի միջոցով ավելի լավ որոշումներ կայացնելն է, ոչ թե գործիքների անուններ հավաքելը։"),
        lesson(102, 2, "Human Judgment First", "Մարդկային դատողությունն առաջնային է", "Recognize which parts of an AI-assisted task must remain under human control.", "Տարբերակեք ԱԲ-աջակցությամբ աշխատանքի այն մասերը, որոնք պետք է մնան մարդու վերահսկողության ներքո։", ["AI can propose, transform, and organize", "People set goals, values, and acceptable risk", "The person using the output remains accountable"], ["ԱԲ-ը կարող է առաջարկել, վերափոխել և կազմակերպել", "Մարդիկ են սահմանում նպատակները, արժեքներն ու ընդունելի ռիսկը", "Արդյունքն օգտագործող մարդը շարունակում է պատասխանատու մնալ"], "Take one familiar task and label each step AI may assist, a human must check, or a human must decide.", "Ընտրեք ծանոթ առաջադրանք և յուրաքանչյուր քայլ նշեք՝ ԱԲ-ը կարող է աջակցել, մարդը պետք է ստուգի, թե մարդը պետք է որոշի։", "Capability does not transfer responsibility from the user to the tool.", "Գործիքի կարողությունը պատասխանատվությունը չի փոխանցում մարդուց ԱԲ-ին։"),
        lesson(103, 3, "Your AI Use Agreement", "ԱԲ-ի օգտագործման ձեր համաձայնագիրը", "Create personal rules for safe, honest, and purposeful AI use.", "Ստեղծեք ԱԲ-ի անվտանգ, ազնիվ և նպատակային օգտագործման անձնական կանոններ։", ["Protect personal, confidential, and sensitive information", "Disclose meaningful AI assistance when required", "Verify important claims before acting or sharing"], ["Պաշտպանել անձնական, գաղտնի և զգայուն տեղեկությունները", "Պահանջի դեպքում նշել ԱԲ-ի նշանակալի աջակցությունը", "Գործելուց կամ տարածելուց առաջ ստուգել կարևոր պնդումները"], "Write four promises beginning with: I will use AI to..., I will never upload..., I will verify..., I will decide....", "Գրեք չորս խոստում՝ «Ես ԱԲ-ը կօգտագործեմ...», «Ես երբեք չեմ բեռնի...», «Ես կստուգեմ...», «Ես ինքս կորոշեմ...» ձևերով։", "A simple agreement turns abstract responsibility into repeatable behavior.", "Պարզ համաձայնագիրը վերածում է վերացական պատասխանատվությունը կրկնվող վարքագծի։")
      ]
    },
    {
      id: 102, sort_order: 2,
      title_en: "Understanding Modern AI", title_hy: "Հասկանալ ժամանակակից ԱԲ-ը",
      quiz_focus_en: "What best describes a large language model response?", quiz_focus_hy: "Ո՞րն է լավագույնս նկարագրում մեծ լեզվական մոդելի պատասխանը։",
      quiz_options_en: ["A generated prediction shaped by training and context", "A guaranteed fact from a database", "A human thought copied exactly", "A private search of every website"],
      quiz_options_hy: ["Ուսուցմամբ և համատեքստով ձևավորված գեներացված կանխատեսում", "Տվյալների բազայից վերցված երաշխավորված փաստ", "Մարդու մտքի ճշգրիտ պատճեն", "Բոլոր կայքերի գաղտնի որոնում"], quiz_correct: 0,
      lessons: [
        lesson(104, 1, "AI, Machine Learning, and Generative AI", "ԱԲ, մեքենայական ուսուցում և գեներատիվ ԱԲ", "Distinguish major AI categories and choose accurate language for each.", "Տարբերակեք ԱԲ-ի հիմնական տեսակները և յուրաքանչյուրի համար կիրառեք ճշգրիտ եզրույթներ։", ["AI is the broad field", "Machine learning finds patterns from data", "Generative AI produces new text, images, audio, video, or code"], ["ԱԲ-ը լայն ոլորտն է", "Մեքենայական ուսուցումը տվյալներից գտնում է օրինաչափություններ", "Գեներատիվ ԱԲ-ը ստեղծում է նոր տեքստ, պատկեր, ձայն, տեսանյութ կամ կոդ"], "Classify five tools you use as rule-based software, predictive AI, or generative AI and explain one uncertain case.", "Ձեր օգտագործած հինգ գործիք դասակարգեք որպես կանոնահեն ծրագիր, կանխատեսող ԱԲ կամ գեներատիվ ԱԲ և բացատրեք մեկ անորոշ դեպք։", "Use the most specific accurate label instead of calling every smart feature AI.", "Յուրաքանչյուր խելացի գործառույթ ԱԲ անվանելու փոխարեն կիրառեք հնարավորինս ճշգրիտ եզրույթ։"),
        lesson(105, 2, "Tokens, Training, and Prediction", "Թոքեններ, ուսուցում և կանխատեսում", "Build an intuitive model of how language models learn and generate text.", "Ձևավորեք պարզ պատկերացում, թե ինչպես են լեզվական մոդելները սովորում և գեներացնում տեքստ։", ["Text is processed as tokens rather than whole ideas", "Training adjusts numerical parameters using many examples", "Generation predicts a useful continuation one step at a time"], ["Տեքստը մշակվում է թոքեններով, ոչ թե ամբողջական գաղափարներով", "Ուսուցումը բազմաթիվ օրինակներով կարգավորում է թվային պարամետրերը", "Գեներացումը քայլ առ քայլ կանխատեսում է օգտակար շարունակությունը"], "Create a six-word sentence, hide the last word, and compare three plausible continuations. Relate this to model uncertainty.", "Գրեք վեց բառանոց նախադասություն, թաքցրեք վերջին բառը և համեմատեք երեք հավանական շարունակություն։ Սա կապեք մոդելի անորոշության հետ։", "Prediction can produce fluent language without guaranteeing truth.", "Կանխատեսումը կարող է ստեղծել սահուն լեզու՝ առանց ճշմարտությունը երաշխավորելու։"),
        lesson(106, 3, "Context, Memory, and Retrieval", "Համատեքստ, հիշողություն և որոնում", "Understand what information a model can use during a conversation.", "Հասկացեք, թե մոդելը զրույցի ընթացքում ինչ տեղեկություն կարող է օգտագործել։", ["The context window contains the current instructions and materials", "Saved memory and chat history are separate product features", "Retrieval can supply selected documents or current sources"], ["Համատեքստի պատուհանը պարունակում է ընթացիկ հրահանգներն ու նյութերը", "Պահված հիշողությունն ու զրույցների պատմությունը առանձին գործառույթներ են", "Որոնումը կարող է տրամադրել ընտրված փաստաթղթեր կամ արդիական աղբյուրներ"], "Ask the same question once without context and once with a short source passage. Compare specificity and traceability.", "Նույն հարցը տվեք մեկ անգամ առանց համատեքստի, ապա՝ կարճ աղբյուր տրամադրելով։ Համեմատեք կոնկրետությունն ու ստուգելիությունը։", "Better context improves relevance; reliable sources improve grounding.", "Ավելի լավ համատեքստը բարձրացնում է համապատասխանությունը, իսկ հուսալի աղբյուրները՝ հիմնավորվածությունը։"),
        lesson(107, 4, "Reasoning, Uncertainty, and Limits", "Տրամաբանում, անորոշություն և սահմանափակումներ", "Evaluate impressive reasoning without assuming the process or conclusion is correct.", "Գնահատեք տպավորիչ տրամաբանությունը՝ առանց գործընթացը կամ եզրակացությունը ինքնաբերաբար ճիշտ համարելու։", ["Models can decompose complex tasks and use tools", "A polished explanation can still contain a faulty premise", "Ask for concise rationale, assumptions, and checkable evidence"], ["Մոդելները կարող են բաժանել բարդ առաջադրանքները և գործիքներ կիրառել", "Հղկված բացատրությունը կարող է հիմնվել սխալ նախադրյալի վրա", "Պահանջեք հակիրճ հիմնավորում, ենթադրություններ և ստուգելի ապացույցներ"], "Give an AI a logic problem, then independently test each assumption instead of judging only the final answer.", "ԱԲ-ին տվեք տրամաբանական խնդիր, ապա ինքնուրույն ստուգեք յուրաքանչյուր ենթադրություն՝ միայն վերջնական պատասխանը չգնահատելով։", "Evaluate the evidence and result, not the confidence or length of the explanation.", "Գնահատեք ապացույցն ու արդյունքը, ոչ թե բացատրության վստահ տոնն ու երկարությունը։")
      ]
    },
    {
      id: 103, sort_order: 3,
      title_en: "Talking to AI", title_hy: "Զրուցել ԱԲ-ի հետ",
      quiz_focus_en: "Which prompt element tells the model how success will be judged?", quiz_focus_hy: "Պրոմփթի ո՞ր բաղադրիչն է մոդելին հայտնում, թե ինչպես է գնահատվելու հաջողությունը։",
      quiz_options_en: ["Review criteria", "A longer greeting", "The tool brand", "More adjectives"], quiz_options_hy: ["Ստուգման չափանիշները", "Ավելի երկար ողջույնը", "Գործիքի ապրանքանիշը", "Ավելի շատ ածականները"], quiz_correct: 0,
      lessons: [
        lesson(108, 1, "Prompting as Clear Communication", "Պրոմփթը որպես հստակ հաղորդակցություն", "Treat prompting as writing a useful brief for a capable collaborator.", "Պրոմփթավորումը դիտարկեք որպես կարող գործընկերոջ համար օգտակար առաջադրանքի կազմում։", ["State the outcome before background detail", "Include only context that changes the answer", "Use direct instructions and define ambiguous terms"], ["Նախ նշեք ցանկալի արդյունքը, ապա՝ նախապատմությունը", "Ներառեք միայն այն համատեքստը, որը փոխում է պատասխանը", "Տվեք ուղիղ հրահանգներ և սահմանեք անորոշ եզրույթները"], "Rewrite a vague request such as 'help with my presentation' into a brief with a goal, audience, and deliverable.", "«Օգնիր շնորհանդեսիս» անորոշ խնդրանքը վերաշարադրեք՝ ավելացնելով նպատակ, լսարան և ակնկալվող արդյունք։", "If another person could not follow the brief, the AI probably cannot either.", "Եթե մեկ այլ մարդ չի կարող հետևել առաջադրանքին, ԱԲ-ը նույնպես հավանաբար չի կարող։"),
        lesson(109, 2, "The CLEAR Brief", "Հստակ առաջադրանքի հինգ բաղադրիչները", "Use a reusable structure for reliable everyday prompts.", "Կիրառեք կրկնակի օգտագործվող կառուցվածք՝ առօրյա հուսալի պրոմփթների համար։", ["Context: what the model needs to know", "Limits and audience: boundaries, tone, and level", "Expected output and review criteria: form and quality"], ["Համատեքստ՝ ինչ պետք է իմանա մոդելը", "Սահմաններ և լսարան՝ սահմանափակում, ոճ և մակարդակ", "Սպասվող արդյունք և ստուգման չափանիշ՝ ձև և որակ"], "Build one CLEAR prompt for a real task, test it, and highlight which sentence serves each component.", "Իրական առաջադրանքի համար կազմեք հստակ պրոմփթ, փորձարկեք այն և նշեք, թե որ նախադասությունն ինչ բաղադրիչ է ներկայացնում։", "A framework is a checklist, not a magic phrase.", "Կառուցվածքը ստուգաթերթ է, ոչ թե կախարդական արտահայտություն։"),
        lesson(110, 3, "Examples, Constraints, and Formats", "Օրինակներ, սահմանափակումներ և ձևաչափեր", "Control quality by showing patterns and defining the shape of the answer.", "Վերահսկեք որակը՝ ցույց տալով օրինակներ և սահմանելով պատասխանի ձևը։", ["Examples demonstrate tone and decision boundaries", "Constraints prevent unsuitable length, content, or style", "Tables, bullets, schemas, and templates make outputs reusable"], ["Օրինակները ցույց են տալիս ոճն ու որոշման սահմանները", "Սահմանափակումները կանխում են անհամապատասխան ծավալը, բովանդակությունը կամ ոճը", "Աղյուսակները, ցանկերը և ձևանմուշները արդյունքը դարձնում են կրկնակի օգտագործելի"], "Request the same information as a paragraph and as a comparison table. Decide which is easier to check and reuse.", "Նույն տեղեկությունը պահանջեք պարբերության և համեմատական աղյուսակի ձևով։ Որոշեք՝ որն է ավելի հեշտ ստուգել ու կրկին օգտագործել։", "Specify the form when the output must fit a real workflow.", "Սահմանեք ձևաչափը, երբ արդյունքը պետք է տեղավորվի իրական աշխատանքային ընթացքի մեջ։"),
        lesson(111, 4, "Iteration and Prompt Debugging", "Փուլային բարելավում և պրոմփթի ուղղում", "Improve an interaction by diagnosing the failure instead of adding random detail.", "Բարելավեք փոխազդեցությունը՝ գտնելով ձախողման պատճառը, ոչ թե պատահական մանրամասներ ավելացնելով։", ["Identify whether the problem is context, instruction, evidence, or format", "Change one important variable at a time", "Keep the best version and record why it worked"], ["Պարզեք՝ խնդիրը համատեքստի, հրահանգի, ապացույցի թե ձևաչափի մեջ է", "Միաժամանակ փոխեք մեկ կարևոր գործոն", "Պահեք լավագույն տարբերակը և գրանցեք՝ ինչու այն աշխատեց"], "Run three versions of one prompt. Keep a short test log with the change, result, and next decision.", "Նույն պրոմփթի երեք տարբերակ փորձարկեք։ Պահեք կարճ գրառում՝ փոփոխություն, արդյունք և հաջորդ որոշում։", "Prompt engineering is an evidence-based improvement loop.", "Պրոմփթների մշակումը ապացույցներով առաջնորդվող բարելավման շրջան է։")
      ]
    },
    {
      id: 104, sort_order: 4,
      title_en: "Checking AI", title_hy: "Ստուգել ԱԲ-ը",
      quiz_focus_en: "What should happen before using an important factual AI claim?", quiz_focus_hy: "Ի՞նչ պետք է անել նախքան ԱԲ-ի կարևոր փաստական պնդումն օգտագործելը։",
      quiz_options_en: ["Trace it to a suitable independent source", "Trust the confident wording", "Ask for a longer answer", "Remove the citation"], quiz_options_hy: ["Հաստատել այն համապատասխան անկախ աղբյուրով", "Վստահել համոզիչ ձևակերպմանը", "Պահանջել ավելի երկար պատասխան", "Հեռացնել հղումը"], quiz_correct: 0,
      lessons: [
        lesson(112, 1, "Hallucinations and Confident Mistakes", "Հորինվածքներ և վստահ հնչող սխալներ", "Recognize why plausible AI output may contain invented or distorted details.", "Հասկացեք, թե ինչու համոզիչ ԱԲ արդյունքը կարող է հորինված կամ աղավաղված մանրամասներ պարունակել։", ["Fluency is not evidence", "Names, dates, quotations, and citations are common failure points", "Higher-stakes claims require stronger verification"], ["Սահուն խոսքը ապացույց չէ", "Անունները, ամսաթվերը, մեջբերումներն ու հղումները հաճախ սխալի աղբյուր են", "Բարձր ռիսկի պնդումները պահանջում են ավելի խիստ ստուգում"], "Ask for five sources on a niche topic and verify that each source exists and supports the stated claim.", "Նեղ թեմայով խնդրեք հինգ աղբյուր և ստուգեք՝ յուրաքանչյուր աղբյուր գոյություն ունի՞ ու աջակցո՞ւմ է նշված պնդմանը։", "Treat unsupported specificity as a signal to investigate.", "Չհիմնավորված կոնկրետությունը համարեք լրացուցիչ ստուգման ազդանշան։"),
        lesson(113, 2, "The TRACE Verification Check", "TRACE ստուգման մեթոդը", "Apply a repeatable check to important AI outputs.", "Կիրառեք կրկնվող մեթոդ՝ ԱԲ-ի կարևոր արդյունքները ստուգելու համար։", ["Trace claims and review source quality", "Assess uncertainty and check missing perspectives", "Escalate legal, medical, financial, safety, or reputational risk"], ["Հետևեք պնդումներին և գնահատեք աղբյուրների որակը", "Գնահատեք անորոշությունն ու բացակայող տեսակետները", "Բարձրացրեք իրավական, բժշկական, ֆինանսական, անվտանգության կամ հեղինակության ռիսկերը"], "Annotate one AI answer with T, R, A, C, and E notes. Rewrite any sentence that remains unsupported.", "Մեկ ԱԲ պատասխանի վրա նշեք TRACE-ի քայլերը և վերաշարադրեք չհիմնավորված նախադասությունները։", "Verification should be visible in the work, not only promised.", "Ստուգումը պետք է տեսանելի լինի աշխատանքում, ոչ միայն խոստացված։"),
        lesson(114, 3, "Source Quality and Live Research", "Աղբյուրների որակ և արդիական հետազոտություն", "Choose sources that are current, relevant, authoritative, and close to the original evidence.", "Ընտրեք արդիական, համապատասխան, հեղինակավոր և սկզբնական ապացույցին մոտ աղբյուրներ։", ["Prefer primary and official sources for factual claims", "Separate publication date from the date an event happened", "Use citations to inspect evidence, not to decorate an answer"], ["Փաստական պնդումների համար նախընտրեք սկզբնական և պաշտոնական աղբյուրներ", "Տարբերակեք հրապարակման ամսաթիվը իրադարձության ամսաթվից", "Հղումները կիրառեք ապացույցը ստուգելու, ոչ թե պատասխանը զարդարելու համար"], "Compare an official source, a news summary, and an anonymous post about the same claim. Rank their usefulness and explain why.", "Նույն պնդման մասին համեմատեք պաշտոնական աղբյուր, լրատվական ամփոփում և անանուն գրառում։ Դասակարգեք դրանց օգտակարությունը և հիմնավորեք։", "A citation is useful only when it leads to evidence that supports the claim.", "Հղումն օգտակար է միայն այն դեպքում, երբ տանում է պնդումը հաստատող ապացույցի։"),
        lesson(115, 4, "Bias, Privacy, Copyright, and Boundaries", "Կողմնակալություն, գաղտնիություն, հեղինակային իրավունք և սահմաններ", "Identify situations where an AI task may harm people, expose data, or misuse creative work.", "Բացահայտեք իրավիճակներ, երբ ԱԲ առաջադրանքը կարող է վնասել մարդկանց, բացահայտել տվյալներ կամ սխալ օգտագործել ստեղծագործ աշխատանքը։", ["Ask whose experience is represented or missing", "Do not upload data you lack permission to share", "Respect authorship, school rules, licenses, and disclosure requirements"], ["Հարցրեք՝ ում փորձն է ներկայացված կամ բացակայում", "Մի բեռնեք տվյալներ, որոնց տարածման թույլտվությունը չունեք", "Հարգեք հեղինակությունը, կրթական կանոնները, արտոնագրերն ու թափանցիկության պահանջները"], "Review a proposed AI task using four questions: who could be affected, what data enters, what rights apply, and should AI be used at all?", "Գնահատեք ԱԲ առաջադրանքը չորս հարցով՝ ով կարող է ազդվել, ինչ տվյալ է մուտքագրվում, ինչ իրավունքներ են գործում և արդյոք ընդհանրապես պետք է կիրառել ԱԲ։", "Sometimes the responsible AI choice is to limit the task or not use AI.", "Երբեմն ԱԲ-ի պատասխանատու ընտրությունը առաջադրանքը սահմանափակելն է կամ ԱԲ չօգտագործելը։")
      ]
    },
    {
      id: 105, sort_order: 5,
      title_en: "Using AI for Real Work", title_hy: "ԱԲ-ը իրական առաջադրանքներում",
      quiz_focus_en: "What is the best role for AI in an assessed piece of work?", quiz_focus_hy: "Ո՞րն է ԱԲ-ի լավագույն դերը գնահատվող աշխատանքում։",
      quiz_options_en: ["Support a transparent process while the learner owns and verifies the work", "Write everything secretly", "Replace source reading", "Make the final judgment"], quiz_options_hy: ["Թափանցիկ աջակցել գործընթացին, մինչ սովորողը տնօրինում և ստուգում է աշխատանքը", "Գաղտնի գրել ամբողջ աշխատանքը", "Փոխարինել աղբյուրների ընթերցումը", "Կայացնել վերջնական որոշումը"], quiz_correct: 0,
      lessons: [
        lesson(116, 1, "Writing, Editing, and Translation", "Գրել, խմբագրել և թարգմանել", "Use AI to improve communication while protecting meaning, voice, and authorship.", "Կիրառեք ԱԲ-ը հաղորդակցությունը բարելավելու համար՝ պահպանելով իմաստը, ձայնն ու հեղինակությունը։", ["Separate drafting, editing, and proofreading", "Give audience, purpose, tone, and non-negotiable facts", "Review translations for cultural meaning and technical accuracy"], ["Տարբերակեք սևագրումը, խմբագրումը և սրբագրումը", "Նշեք լսարանը, նպատակը, ոճը և անփոփոխ փաստերը", "Թարգմանությունը ստուգեք մշակութային իմաստի և մասնագիտական ճշգրտության համար"], "Edit one paragraph with AI, compare it line by line with your original, and restore anything that changed your intended meaning.", "ԱԲ-ով խմբագրեք մեկ պարբերություն, համեմատեք բնագրի հետ տող առ տող և վերականգնեք այն, ինչ փոխել է ձեր նախատեսած իմաստը։", "A cleaner sentence is not an improvement if it stops sounding like you or changes the facts.", "Ավելի հարթ նախադասությունը բարելավում չէ, եթե այն այլևս ձեր ձայնով չէ կամ փոխում է փաստերը։"),
        lesson(117, 2, "Ideation, Planning, and Decisions", "Գաղափարներ, պլանավորում և որոշումներ", "Generate options without outsourcing priorities or final choices.", "Ստեղծեք տարբերակներ՝ առանց առաջնահերթություններն ու վերջնական ընտրությունը ԱԲ-ին փոխանցելու։", ["Diverge first: ask for varied possibilities", "Converge with explicit criteria and constraints", "Record assumptions and let the responsible person decide"], ["Սկզբում ընդլայնեք՝ պահանջելով տարբեր հնարավորություններ", "Ապա ընտրեք՝ հստակ չափանիշներով և սահմանափակումներով", "Գրանցեք ենթադրությունները և որոշումը թողեք պատասխանատու մարդուն"], "Generate ten project ideas, score them against three criteria you chose, and explain why your final choice may differ from the model's ranking.", "Ստեղծեք տասը նախագծային գաղափար, գնահատեք ձեր ընտրած երեք չափանիշով և բացատրեք՝ ինչու ձեր վերջնական ընտրությունը կարող է տարբերվել մոդելի վարկանիշից։", "AI can expand and organize choices; values determine the decision.", "ԱԲ-ը կարող է ընդլայնել և կազմակերպել ընտրությունները, իսկ արժեքները որոշում են վերջնական քայլը։"),
        lesson(118, 3, "Learning, Tutoring, and Research", "Ուսուցում, անհատական պարապմունք և հետազոտություն", "Use AI to strengthen understanding rather than bypass productive effort.", "Կիրառեք ԱԲ-ը ըմբռնումը խորացնելու, ոչ թե օգտակար մտավոր ջանքը շրջանցելու համար։", ["Ask for questions, hints, feedback, and alternative explanations", "Retrieve and read original sources for research", "Demonstrate understanding in your own words and examples"], ["Պահանջեք հարցեր, հուշումներ, հետադարձ կապ և այլընտրանքային բացատրություններ", "Հետազոտության համար գտեք և կարդացեք սկզբնական աղբյուրները", "Ըմբռնումը ցույց տվեք ձեր բառերով և օրինակներով"], "Ask an AI tutor to guide you using questions only. Afterward, solve a similar problem without assistance.", "ԱԲ ուսուցչին խնդրեք ուղղորդել ձեզ միայն հարցերով։ Այնուհետև նման խնդիր լուծեք առանց աջակցության։", "Learning occurs when you can explain, transfer, and apply the idea yourself.", "Ուսուցումը տեղի է ունենում, երբ ինքնուրույն կարողանում եք բացատրել, տեղափոխել և կիրառել գաղափարը։"),
        lesson(119, 4, "Working with Images, Audio, Files, and Data", "Պատկերներ, ձայն, ֆայլեր և տվյալներ", "Give precise instructions for multimodal tasks and inspect what the model may have missed.", "Բազմամոդալ առաջադրանքների համար տվեք ճշգրիտ հրահանգներ և ստուգեք՝ ինչ կարող էր բաց թողնել մոդելը։", ["Refer explicitly to the relevant part of each input", "Ask for structured extraction before interpretation", "Check small text, numbers, labels, units, and missing context"], ["Հստակ հղվեք յուրաքանչյուր մուտքի համապատասխան հատվածին", "Մեկնաբանությունից առաջ պահանջեք կառուցվածքային արտահանում", "Ստուգեք մանր տեքստը, թվերը, պիտակները, միավորներն ու բացակայող համատեքստը"], "Use a public chart or image. Ask for a structured description, then compare every stated detail with the original.", "Օգտագործեք հանրային գծապատկեր կամ պատկեր։ Պահանջեք կառուցվածքային նկարագրություն, ապա յուրաքանչյուր մանրամասն համեմատեք բնագրի հետ։", "Multimodal confidence must be checked against the original media.", "Բազմամոդալ պատասխանի վստահությունը պետք է ստուգել սկզբնական մեդիայի հետ։")
      ]
    },
    {
      id: 106, sort_order: 6,
      title_en: "Creating AI Characters and Tutors", title_hy: "ԱԲ կերպարների և ուսուցիչների ստեղծում",
      quiz_focus_en: "What makes an AI character safer and more useful?", quiz_focus_hy: "Ի՞նչն է ԱԲ կերպարը դարձնում ավելի անվտանգ և օգտակար։",
      quiz_options_en: ["A clear purpose, boundaries, and tests", "A famous person's identity", "Unlimited authority", "Hidden instructions"], quiz_options_hy: ["Հստակ նպատակ, սահմաններ և փորձարկումներ", "Հայտնի մարդու ինքնություն", "Անսահմանափակ լիազորություն", "Թաքնված հրահանգներ"], quiz_correct: 0,
      lessons: [
        lesson(120, 1, "Character, Role, and Expertise", "Կերպար, դեր և մասնագիտական գիտելիք", "Separate a designed conversational role from verified expertise or real identity.", "Տարբերակեք նախագծված հաղորդակցական դերը հաստատված մասնագիտական գիտելիքից կամ իրական ինքնությունից։", ["A role can guide tone, method, and vocabulary", "A convincing persona does not add factual authority", "Avoid deceptive impersonation of real people"], ["Դերը կարող է ուղղորդել ոճը, մեթոդն ու բառապաշարը", "Համոզիչ կերպարը չի ավելացնում փաստական հեղինակություն", "Խուսափեք իրական մարդկանց խաբուսիկ նմանակումից"], "Design a fictional study coach and state three things it must never claim or decide.", "Նախագծեք հորինված ուսումնական մարզիչ և նշեք երեք բան, որոնք այն երբեք չպետք է պնդի կամ որոշի։", "Personality changes the interaction, not the truth of the content.", "Անհատականությունը փոխում է փոխազդեցությունը, ոչ թե բովանդակության ճշմարտացիությունը։"),
        lesson(121, 2, "Voice, Context, and Boundaries", "Ոճ, համատեքստ և սահմաններ", "Write character instructions that support a specific learner and purpose.", "Կազմեք կերպարի հրահանգներ, որոնք աջակցում են կոնկրետ սովորողի և նպատակի։", ["Define the audience, goal, tone, and teaching method", "Specify what information the character may use", "Add refusal, uncertainty, and escalation rules"], ["Սահմանեք լսարանը, նպատակը, ոճն ու ուսուցման մեթոդը", "Նշեք՝ կերպարը ինչ տեղեկություն կարող է օգտագործել", "Ավելացրեք մերժման, անորոշության և օգնության դիմելու կանոններ"], "Write a one-page character card and test it with a normal request, an ambiguous request, and an unsafe request.", "Կազմեք մեկ էջանոց կերպարի քարտ և փորձարկեք սովորական, անորոշ ու անապահով հարցմամբ։", "Good boundaries are visible in difficult conversations, not only in the description.", "Լավ սահմանները երևում են բարդ զրույցներում, ոչ միայն նկարագրության մեջ։"),
        lesson(122, 3, "Memory, Personalization, and Testing", "Հիշողություն, անհատականացում և փորձարկում", "Personalize an AI experience without collecting unnecessary personal data.", "Անհատականացրեք ԱԲ փորձառությունը՝ առանց ավելորդ անձնական տվյալներ հավաքելու։", ["Store preferences only when they serve a clear purpose", "Let users inspect, correct, and remove remembered information", "Test consistency, privacy, bias, and failure recovery"], ["Նախընտրությունները պահեք միայն հստակ նպատակի համար", "Օգտվողին հնարավորություն տվեք դիտել, ուղղել և հեռացնել հիշվող տվյալները", "Փորձարկեք հետևողականությունը, գաղտնիությունը, կողմնակալությունն ու վերականգնումը"], "Create a five-case test sheet for your character and record expected versus actual behavior.", "Ձեր կերպարի համար կազմեք հինգ դեպքից բաղկացած փորձարկման թերթ և գրանցեք սպասվող ու իրական վարքը։", "Personalization should increase usefulness without reducing user control.", "Անհատականացումը պետք է բարձրացնի օգտակարությունը՝ չնվազեցնելով օգտվողի վերահսկողությունը։")
      ]
    },
    {
      id: 107, sort_order: 7,
      title_en: "Choosing AI Tools", title_hy: "ԱԲ գործիքների ընտրություն",
      quiz_focus_en: "What is the strongest basis for choosing an AI tool?", quiz_focus_hy: "Ո՞րն է ԱԲ գործիք ընտրելու ամենաուժեղ հիմքը։",
      quiz_options_en: ["A test against the task, evidence, privacy, cost, and access needs", "The loudest advertisement", "One viral ranking", "The longest feature list"], quiz_options_hy: ["Առաջադրանքի, ապացույցների, գաղտնիության, արժեքի և հասանելիության պահանջներով փորձարկումը", "Ամենաաղմկոտ գովազդը", "Մեկ տարածված վարկանիշը", "Ամենաերկար գործառույթների ցանկը"], quiz_correct: 0,
      lessons: [
        lesson(123, 1, "A Map of AI Tool Categories", "ԱԲ գործիքների տեսակների քարտեզ", "Match tool categories to the outcome you need.", "Համապատասխանեցրեք գործիքի տեսակը ձեր ակնկալվող արդյունքին։", ["Chat tools support conversation and transformation", "Search and research tools retrieve current sources", "Creation, coding, and automation tools produce or change artifacts"], ["Զրույցի գործիքներն աջակցում են հաղորդակցությանը և վերափոխմանը", "Որոնման և հետազոտության գործիքները գտնում են արդիական աղբյուրներ", "Ստեղծման, ծրագրավորման և ավտոմատացման գործիքները ստեղծում կամ փոխում են նյութեր"], "Place ten familiar AI features on a category map and note which combine more than one category.", "Տասը ծանոթ ԱԲ գործառույթ տեղադրեք տեսակների քարտեզի վրա և նշեք՝ որոնք են միավորում մի քանի տեսակ։", "Choose the tool category before choosing the brand.", "Նախ ընտրեք գործիքի տեսակը, հետո՝ ապրանքանիշը։"),
        lesson(124, 2, "Models, Features, Access, and Data", "Մոդելներ, գործառույթներ, հասանելիություն և տվյալներ", "Compare what a product can do and what using it requires from the learner.", "Համեմատեք՝ ինչ կարող է անել գործիքը և դրա օգտագործումն ինչ է պահանջում սովորողից։", ["Products may combine models, web access, file tools, memory, and apps", "Free and paid access can differ by limits and data controls", "School or workplace rules may matter more than raw capability"], ["Գործիքները կարող են միավորել մոդելներ, վեբ հասանելիություն, ֆայլեր, հիշողություն և հավելվածներ", "Անվճար և վճարովի հասանելիությունը կարող է տարբերվել սահմանաչափերով ու տվյալների վերահսկմամբ", "Կրթական կամ աշխատանքային կանոնները կարող են ավելի կարևոր լինել, քան մոդելի ուժը"], "For two tools, record access requirements, supported inputs, source behavior, data controls, and limits. Do not record passwords or private account data.", "Երկու գործիքի համար գրանցեք հասանելիության պահանջները, մուտքերի տեսակները, աղբյուրների վարքը, տվյալների վերահսկումն ու սահմանաչափերը։ Մի գրանցեք գաղտնաբառեր կամ անձնական հաշվի տվյալներ։", "A feature is useful only when it fits your access, policy, and risk context.", "Գործառույթն օգտակար է միայն այն դեպքում, երբ համապատասխանում է ձեր հասանելիությանը, կանոններին ու ռիսկին։"),
        lesson(125, 3, "The Tool Evaluation Scorecard", "Գործիքների գնահատման ստուգաթերթ", "Run a fair, repeatable comparison instead of relying on popularity.", "Կատարեք արդար և կրկնվող համեմատություն՝ հանրաճանաչության վրա հենվելու փոխարեն։", ["Use the same realistic task and input for each tool", "Score quality, evidence, privacy, speed, cost, and accessibility", "Record the date because products and capabilities change"], ["Յուրաքանչյուր գործիքի համար կիրառեք նույն իրական առաջադրանքն ու մուտքը", "Գնահատեք որակը, ապացույցները, գաղտնիությունը, արագությունը, արժեքը և մատչելիությունը", "Գրանցեք ամսաթիվը, քանի որ գործիքներն ու հնարավորությունները փոխվում են"], "Compare three tools with the scorecard, then write a recommendation for one specific user and task.", "Ստուգաթերթով համեմատեք երեք գործիք, ապա առաջարկեք մեկը կոնկրետ օգտվողի և առաջադրանքի համար։", "The best tool is conditional: best for whom, for what, under which constraints?","Լավագույն գործիքը պայմանական է՝ ո՞ւմ համար, ի՞նչ նպատակով և ի՞նչ սահմանափակումներով։")
      ]
    },
    {
      id: 108, sort_order: 8,
      title_en: "From Chatbots to Agents", title_hy: "Զրուցարաններից մինչև ԱԲ գործակալներ",
      quiz_focus_en: "What should an agent require before a consequential external action?", quiz_focus_hy: "Ի՞նչ պետք է պահանջի գործակալը կարևոր արտաքին գործողությունից առաջ։",
      quiz_options_en: ["Explicit human approval with a clear preview", "More autonomy by default", "A hidden action log", "Access to every account"], quiz_options_hy: ["Մարդու հստակ հաստատում՝ գործողության պարզ նախադիտմամբ", "Լռելյայն ավելի մեծ ինքնավարություն", "Թաքնված գործողությունների գրանցում", "Բոլոր հաշիվների հասանելիություն"], quiz_correct: 0,
      lessons: [
        lesson(126, 1, "Tools, Workflows, and Agents", "Գործիքներ, աշխատանքային ընթացքներ և գործակալներ", "Understand the difference between generating an answer and taking actions across steps.", "Տարբերակեք պատասխանի ստեղծումը բազմափուլ գործողությունների կատարումից։", ["A tool performs a bounded action", "A workflow connects defined steps", "An agent chooses and carries out steps toward a goal"], ["Գործիքը կատարում է սահմանափակ գործողություն", "Աշխատանքային ընթացքը կապում է սահմանված քայլերը", "Գործակալն ընտրում և կատարում է քայլեր՝ նպատակին հասնելու համար"], "Turn a simple goal into a diagram of inputs, decisions, tools, outputs, and human checkpoints.", "Պարզ նպատակը ներկայացրեք մուտքերի, որոշումների, գործիքների, արդյունքների և մարդու հաստատման կետերի գծապատկերով։", "More autonomy increases the need for permissions, observation, and recovery.", "Ավելի մեծ ինքնավարությունը մեծացնում է թույլտվությունների, դիտարկման և վերականգնման պահանջը։"),
        lesson(127, 2, "Research with Live Sources", "Հետազոտություն արդիական աղբյուրներով", "Plan a multi-step research task that produces traceable findings.", "Պլանավորեք բազմափուլ հետազոտություն, որը տալիս է ստուգելի արդյունքներ։", ["Define the question, timeframe, geography, and source standard", "Review the research plan before execution", "Open citations and check whether they support each claim"], ["Սահմանեք հարցը, ժամանակահատվածը, աշխարհագրությունը և աղբյուրների չափանիշը", "Կատարումից առաջ վերանայեք հետազոտության պլանը", "Բացեք հղումները և ստուգեք՝ արդյոք դրանք հաստատում են յուրաքանչյուր պնդում"], "Commission a short source-backed comparison, then verify three claims and document one limitation in the search.", "Պատվիրեք աղբյուրներով հիմնավորված կարճ համեմատություն, ապա ստուգեք երեք պնդում և փաստագրեք որոնման մեկ սահմանափակում։", "Agentic research accelerates discovery; the learner still evaluates evidence.", "Գործակալային հետազոտությունն արագացնում է բացահայտումը, սակայն ապացույցը շարունակում է գնահատել սովորողը։"),
        lesson(128, 3, "Automating Repetitive Work", "Կրկնվող աշխատանքի ավտոմատացում", "Identify safe automation opportunities and calculate whether they are worth building.", "Բացահայտեք անվտանգ ավտոմատացման հնարավորություններ և գնահատեք՝ արդյոք դրանք արժե իրականացնել։", ["Choose stable, frequent, and clearly defined tasks", "Keep inputs and outputs structured", "Measure time saved, error rate, and review effort"], ["Ընտրեք կայուն, հաճախակի և հստակ սահմանված առաջադրանքներ", "Մուտքերն ու արդյունքները պահեք կառուցվածքային", "Չափեք խնայված ժամանակը, սխալների մակարդակը և ստուգման ջանքը"], "List five repeated tasks and rank them by frequency, risk, clarity, and potential time saved. Select one low-risk candidate.", "Թվարկեք հինգ կրկնվող առաջադրանք և դասակարգեք ըստ հաճախականության, ռիսկի, հստակության ու հնարավոր ժամանակի խնայողության։ Ընտրեք մեկ ցածր ռիսկի թեկնածու։", "Automate stable repetition before uncertain judgment.", "Նախ ավտոմատացրեք կայուն կրկնությունը, ոչ թե անորոշ դատողությունը։"),
        lesson(129, 4, "Permissions, Approval, and Recovery", "Թույլտվություններ, հաստատում և վերականգնում", "Design controls for an AI system that can affect files, accounts, money, or people.", "Նախագծեք վերահսկողություն այն ԱԲ համակարգի համար, որը կարող է ազդել ֆայլերի, հաշիվների, գումարի կամ մարդկանց վրա։", ["Grant the minimum access needed for the task", "Preview consequential actions before a person approves them", "Keep logs, stop controls, backups, and a recovery path"], ["Տվեք միայն առաջադրանքի համար անհրաժեշտ նվազագույն հասանելիությունը", "Կարևոր գործողությունները նախադիտեք մինչև մարդու հաստատումը", "Պահեք գրանցումներ, կանգնեցման միջոցներ, կրկնօրինակներ և վերականգնման ուղի"], "Create a failure table for one automation: possible failure, warning signal, prevention, stop condition, and recovery action.", "Մեկ ավտոմատացման համար կազմեք խափանման աղյուսակ՝ հնարավոր սխալ, ազդանշան, կանխարգելում, կանգնեցման պայման և վերականգնման քայլ։", "A safe agent is designed to ask, show, stop, and recover.", "Անվտանգ գործակալը պետք է կարողանա հարցնել, ցույց տալ, կանգ առնել և վերականգնվել։")
      ]
    },
    {
      id: 109, sort_order: 9,
      title_en: "Practical Matters", title_hy: "Գործնական հարցեր",
      quiz_focus_en: "Why should prompt and source versions be recorded?", quiz_focus_hy: "Ինչո՞ւ պետք է գրանցել պրոմփթի և աղբյուրների տարբերակները։",
      quiz_options_en: ["To reproduce, compare, and improve the work", "To make the file longer", "To hide AI use", "To avoid checking outputs"], quiz_options_hy: ["Աշխատանքը վերարտադրելու, համեմատելու և բարելավելու համար", "Ֆայլը երկարացնելու համար", "ԱԲ-ի օգտագործումը թաքցնելու համար", "Արդյունքները չստուգելու համար"], quiz_correct: 0,
      lessons: [
        lesson(130, 1, "Tokens, Limits, Time, and Cost", "Թոքեններ, սահմանաչափեր, ժամանակ և արժեք", "Estimate AI effort without relying on prices or limits that quickly become outdated.", "Գնահատեք ԱԲ աշխատանքի ծավալը՝ առանց արագ հնացող գների կամ սահմանաչափերի վրա հենվելու։", ["Input, output, media, tools, and repeated attempts can affect cost", "Longer is not automatically better", "Select capability and effort proportional to the task"], ["Մուտքը, արդյունքը, մեդիան, գործիքները և կրկնվող փորձերը կարող են ազդել արժեքի վրա", "Ավելի երկար պատասխանը ինքնաբերաբար ավելի լավ չէ", "Ընտրեք առաջադրանքին համաչափ կարողություն և ջանք"], "Estimate a small workflow in number of runs, documents, review minutes, and acceptable cost. Then identify one way to simplify it.", "Փոքր աշխատանքային ընթացքը գնահատեք փորձերի, փաստաթղթերի, ստուգման րոպեների և ընդունելի արժեքի չափով։ Ապա գտեք այն պարզեցնելու մեկ եղանակ։", "Optimize the whole workflow, including human review, not only token count.", "Օպտիմալացրեք ամբողջ ընթացքը՝ ներառյալ մարդկային ստուգումը, ոչ միայն թոքենների քանակը։"),
        lesson(131, 2, "Managing Context, Files, and Sources", "Համատեքստի, ֆայլերի և աղբյուրների կառավարում", "Prepare source material so the model and the learner can trace what matters.", "Պատրաստեք աղբյուրները այնպես, որ մոդելն ու սովորողը կարողանան հետևել կարևոր տեղեկությանը։", ["Name files clearly and record origin, date, and permissions", "Separate instructions from untrusted document content", "Provide only relevant material and protect sensitive data"], ["Ֆայլերը հստակ անվանեք և գրանցեք ծագումը, ամսաթիվն ու թույլտվությունները", "Հրահանգները տարբերակեք չվստահված փաստաթղթի բովանդակությունից", "Տրամադրեք միայն համապատասխան նյութ և պաշտպանեք զգայուն տվյալները"], "Organize three public sources into a small source pack with filenames, one-line descriptions, dates, and allowed uses.", "Երեք հանրային աղբյուր կազմակերպեք փոքր փաթեթում՝ ֆայլի անուն, մեկ տողանոց նկարագրություն, ամսաթիվ և թույլատրելի օգտագործում։", "Good context management improves both model performance and human auditability.", "Համատեքստի ճիշտ կառավարումը բարելավում է և՛ մոդելի արդյունքը, և՛ մարդու կողմից ստուգելիությունը։"),
        lesson(132, 3, "Prompt Versions and Team Rules", "Պրոմփթների տարբերակներ և թիմային կանոններ", "Make successful AI-assisted work reproducible and understandable to others.", "ԱԲ-աջակցությամբ հաջող աշխատանքը դարձրեք վերարտադրելի և հասկանալի ուրիշների համար։", ["Save prompts with purpose, owner, date, and version", "Record test cases and known limitations", "Agree on permitted data, required review, and disclosure"], ["Պրոմփթները պահեք նպատակով, պատասխանատուով, ամսաթվով և տարբերակով", "Գրանցեք փորձարկման դեպքերն ու հայտնի սահմանափակումները", "Համաձայնեցրեք թույլատրելի տվյալները, պարտադիր ստուգումն ու թափանցիկությունը"], "Create a prompt card and a five-rule team policy for a shared classroom or project workflow.", "Ստեղծեք պրոմփթի քարտ և հինգ կանոնից բաղկացած թիմային քաղաքականություն՝ ընդհանուր դասարանային կամ նախագծային աշխատանքի համար։", "Reusable AI work needs documentation, ownership, and agreed boundaries.", "Կրկնակի օգտագործվող ԱԲ աշխատանքը պահանջում է փաստագրում, պատասխանատու և համաձայնեցված սահմաններ։")
      ]
    },
    {
      id: 110, sort_order: 10,
      title_en: "Capstone, Glossary, and Resources", title_hy: "Ամփոփիչ նախագիծ, բառարան և ռեսուրսներ",
      quiz_focus_en: "What evidence should accompany a strong AI capstone?", quiz_focus_hy: "Ի՞նչ ապացույց պետք է ուղեկցի ուժեղ ԱԲ ամփոփիչ նախագծին։",
      quiz_options_en: ["Tests, sources, limitations, and a human judgment statement", "Only a polished screenshot", "Only the model name", "A claim that it always works"], quiz_options_hy: ["Փորձարկումներ, աղբյուրներ, սահմանափակումներ և մարդկային դատողության հայտարարություն", "Միայն հղկված սքրինշոթ", "Միայն մոդելի անունը", "Պնդում, որ այն միշտ աշխատում է"], quiz_correct: 0,
      lessons: [
        lesson(133, 1, "Plan Your Capstone", "Պլանավորեք ամփոփիչ նախագիծը", "Define a useful, feasible, and responsible AI-assisted solution to a real need.", "Սահմանեք իրական կարիքի օգտակար, իրագործելի և պատասխանատու ԱԲ-աջակցությամբ լուծում։", ["Name the user, need, desired outcome, and success criteria", "Choose the smallest useful prototype", "Identify data, safety, access, and human oversight requirements"], ["Նշեք օգտվողին, կարիքը, ակնկալվող արդյունքն ու հաջողության չափանիշները", "Ընտրեք ամենափոքր օգտակար նախատիպը", "Բացահայտեք տվյալների, անվտանգության, հասանելիության և մարդկային վերահսկողության պահանջները"], "Complete a one-page brief for a study, campus, or community problem and receive feedback from one potential user.", "Լրացրեք մեկ էջանոց առաջադրանք ուսումնական, համալսարանական կամ համայնքային խնդրի համար և ստացեք մեկ հնարավոր օգտվողի կարծիքը։", "A strong project begins with a real need and a testable definition of success.", "Ուժեղ նախագիծը սկսվում է իրական կարիքից և հաջողության ստուգելի սահմանումից։"),
        lesson(134, 2, "Test, Document, and Present", "Փորձարկեք, փաստագրեք և ներկայացրեք", "Demonstrate what the solution does, where it fails, and how people stay in control.", "Ցույց տվեք՝ ինչ է անում լուծումը, որտեղ է ձախողվում և ինչպես է մարդը պահպանում վերահսկողությունը։", ["Test normal, edge, ambiguous, and unsafe cases", "Keep evidence of changes between versions", "Present benefits, limitations, sources, and next steps"], ["Փորձարկեք սովորական, սահմանային, անորոշ և անապահով դեպքեր", "Պահեք տարբերակների միջև փոփոխությունների ապացույցը", "Ներկայացրեք օգուտները, սահմանափակումները, աղբյուրներն ու հաջորդ քայլերը"], "Run at least five tests, improve one weakness, and prepare a three-minute demonstration with a human judgment statement.", "Կատարեք առնվազն հինգ փորձարկում, բարելավեք մեկ թուլություն և պատրաստեք երեք րոպեանոց ցուցադրում՝ մարդկային դատողության հայտարարությամբ։", "A credible demonstration includes failures and safeguards, not only the best result.", "Վստահելի ցուցադրումը ներառում է նաև ձախողումներն ու պաշտպանիչ միջոցները, ոչ միայն լավագույն արդյունքը։"),
        lesson(135, 3, "Glossary, Resources, and Your Next Step", "Բառարան, ռեսուրսներ և ձեր հաջորդ քայլը", "Consolidate core vocabulary and create a plan for continued responsible learning.", "Ամրապնդեք հիմնական բառապաշարը և կազմեք պատասխանատու շարունակական ուսուցման պլան։", ["Explain key terms in your own words", "Prefer current official documentation and primary sources", "Revisit your AI use agreement as capabilities change"], ["Հիմնական եզրույթները բացատրեք ձեր բառերով", "Նախընտրեք արդիական պաշտոնական փաստաթղթեր և սկզբնական աղբյուրներ", "Հնարավորությունների փոփոխությանը զուգահեռ վերանայեք ԱԲ-ի օգտագործման համաձայնագիրը"], "Create a ten-term personal glossary and bookmark official learning resources from OpenAI Academy, UNESCO, Anthropic, and Google.", "Ստեղծեք տասը եզրույթից բաղկացած անձնական բառարան և պահեք OpenAI Academy-ի, ՅՈՒՆԵՍԿՕ-ի, Anthropic-ի ու Google-ի պաշտոնական ուսումնական ռեսուրսները։", "AI literacy is a continuing practice of learning, testing, checking, and deciding.", "ԱԲ գրագիտությունը սովորելու, փորձարկելու, ստուգելու և որոշելու շարունակական գործելակերպ է։")
      ]
    }
  ];

  modules[9].lessons[2].resources = [
    { title_en: "OpenAI Academy", title_hy: "OpenAI Academy", href: "https://academy.openai.com/" },
    { title_en: "UNESCO AI Competency Framework for Students", title_hy: "ՅՈՒՆԵՍԿՕ-ի ԱԲ կարողությունների շրջանակը սովորողների համար", href: "https://www.unesco.org/en/articles/ai-competency-framework-students" },
    { title_en: "Anthropic prompting best practices", title_hy: "Anthropic-ի պրոմփթավորման արդիական ուղեցույց", href: "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/prompt-templates-and-variables" },
    { title_en: "Google prompt design strategies", title_hy: "Google-ի պրոմփթների նախագծման ուղեցույց", href: "https://ai.google.dev/gemini-api/docs/prompting-strategies" }
  ];

  const universalQuiz = [
    {
      question_en: "When an AI output appears complete and confident, what should you do before using it?",
      question_hy: "Երբ ԱԲ-ի արդյունքը լիարժեք և համոզիչ է թվում, ի՞նչ պետք է անել այն օգտագործելուց առաջ։",
      options_en: ["Check the important claims, assumptions, and risks", "Use it immediately", "Remove all uncertainty", "Assume citations are correct"],
      options_hy: ["Ստուգել կարևոր պնդումները, ենթադրություններն ու ռիսկերը", "Անմիջապես օգտագործել", "Հեռացնել անորոշության բոլոր նշումները", "Ենթադրել, որ հղումները ճիշտ են"],
      correct_index: 0
    },
    {
      question_en: "Who remains responsible for a decision or submission supported by AI?",
      question_hy: "Ո՞վ է շարունակում պատասխանատու մնալ ԱԲ-ի աջակցությամբ որոշման կամ ներկայացված աշխատանքի համար։",
      options_en: ["The person or team using the output", "The chatbot alone", "Nobody", "The first website cited"],
      options_hy: ["Արդյունքն օգտագործող մարդը կամ թիմը", "Միայն զրուցարանը", "Ոչ ոք", "Առաջին նշված կայքը"],
      correct_index: 0
    }
  ];

  return {
    slug: "ai-explorers",
    title_en: "AI Explorers",
    title_hy: "ԱԲ բացահայտողներ",
    modules,
    universalQuiz,
    lesson_count: modules.reduce((total, module) => total + module.lessons.length, 0)
  };
});
