(function () {
  "use strict";

  const ui = {
    en: {
      skip: "Skip to content", brand: "EUA AI Academy", allCourses: "All in-person courses", language: "Language", apply: "Apply", back: "← In-person courses", heroEyebrow: "Professional in-person course", reserve: "Reserve your place <span aria-hidden=\"true\">↓</span>",
      outcomesEyebrow: "Practical outcomes", outcomesTitle: "Leave with a working AI system - not just notes.", stateEyebrow: "State of the field", curriculumEyebrow: "Course outline", curriculumTitle: "Four sessions. One complete workflow.", curriculumCopy: "Each two-hour session combines current industry practice, guided tool work, and applied exercises using realistic professional scenarios.",
      toolsEyebrow: "Tool stack", toolsTitle: "Top tools, selected for the work.", toolsNote: "Tool availability may change. Participants learn transferable workflow principles, not dependency on one product.", capstoneEyebrow: "Final project", enrollEyebrow: "Enrollment interest", enrollTitle: "Join the next cohort.", enrollCopy: "Classes are limited to 20 participants. Submit your interest and the EUA AI Academy team will contact you with dates, tuition, and admission details.", includedTitle: "Included", includedCopy: "8 contact hours, guided practice, reusable templates, final-project feedback, and a completion record.",
      firstName: "First name *", lastName: "Last name *", email: "Email *", phone: "Phone", role: "Role / position *", organization: "Organization", message: "What would you like to improve with AI?", submit: "Submit interest", weeks: "weeks", sessions: "live sessions", hours: "contact hours", participants: "participants maximum", session: "Session", weekDay: "Week {w} · Day {d}", lab: "Applied lab", saving: "Submitting your interest…", success: "Thank you. Your interest has been recorded; our team will contact you.", error: "We could not submit your interest. Please try again.", meta: "Two-week, in-person AI course for professionals at EUA AI Academy."
    },
    hy: {
      skip: "Անցնել բովանդակությանը", brand: "ՀԵՀ ԱԲ ակադեմիա", allCourses: "Բոլոր առկա դասընթացները", language: "Լեզու", apply: "Դիմել", back: "← Առկա դասընթացներ", heroEyebrow: "Մասնագիտական առկա դասընթաց", reserve: "Ամրագրել տեղը <span aria-hidden=\"true\">↓</span>",
      outcomesEyebrow: "Գործնական արդյունքներ", outcomesTitle: "Դասընթացն ավարտեք աշխատող ԱԲ համակարգով, ոչ միայն գրառումներով։", stateEyebrow: "Ոլորտի ներկա վիճակը", curriculumEyebrow: "Դասընթացի ծրագիր", curriculumTitle: "Չորս հանդիպում։ Մեկ ամբողջական գործընթաց։", curriculumCopy: "Յուրաքանչյուր երկժամյա հանդիպում համատեղում է ոլորտի արդի փորձը, գործիքներով ուղղորդված աշխատանքը և իրական մասնագիտական իրավիճակների վրա հիմնված վարժությունները։",
      toolsEyebrow: "Գործիքակազմ", toolsTitle: "Առաջատար գործիքներ՝ ընտրված ըստ աշխատանքի։", toolsNote: "Գործիքների հասանելիությունը կարող է փոխվել։ Մասնակիցները սովորում են փոխանցելի աշխատանքային սկզբունքներ, ոչ թե կախվածություն մեկ արտադրանքից։", capstoneEyebrow: "Եզրափակիչ նախագիծ", enrollEyebrow: "Գրանցման հայտ", enrollTitle: "Միացեք հաջորդ խմբին։", enrollCopy: "Խմբում կարող է լինել առավելագույնը 20 մասնակից։ Ուղարկեք ձեր հետաքրքրության հայտը, և ՀԵՀ ԱԲ ակադեմիայի թիմը կկապվի ձեզ հետ՝ ամսաթվերի, վարձավճարի և ընդունելության մանրամասներով։", includedTitle: "Ներառված է", includedCopy: "8 լսարանային ժամ, ուղղորդված գործնական աշխատանք, բազմակի օգտագործման ձևանմուշներ, եզրափակիչ նախագծի հետադարձ կապ և ավարտի գրանցում։",
      firstName: "Անուն *", lastName: "Ազգանուն *", email: "Էլ. փոստ *", phone: "Հեռախոս", role: "Դեր / պաշտոն *", organization: "Կազմակերպություն", message: "Ի՞նչ կցանկանայիք բարելավել ԱԲ-ի միջոցով։", submit: "Ուղարկել հայտը", weeks: "շաբաթ", sessions: "առկա հանդիպում", hours: "լսարանային ժամ", participants: "առավելագույն մասնակից", session: "Հանդիպում", weekDay: "Շաբաթ {w} · Օր {d}", lab: "Գործնական աշխատանք", saving: "Ձեր հայտն ուղարկվում է…", success: "Շնորհակալություն։ Ձեր հայտը գրանցված է, և մեր թիմը կկապվի ձեզ հետ։", error: "Չհաջողվեց ուղարկել հայտը։ Խնդրում ենք կրկին փորձել։", meta: "Երկշաբաթյա մասնագիտական առկա ԱԲ դասընթաց ՀԵՀ ԱԲ ակադեմիայում։"
    }
  };

  const courses = {
    "business-management": {
      en: {
        title: "AI for Business & Management", audience: "For managers, team leads, MBA and business students", summary: "Use AI to sharpen decisions, redesign operations, and lead adoption with measurable business value and responsible oversight.", outcome: "Build an AI-enabled management operating system for a real team or business process, with clear human approvals and performance measures.",
        outcomes: [["Strategic judgment", "Evaluate AI opportunities by value, feasibility, risk, and organizational readiness."], ["Management workflows", "Improve research, meeting preparation, reporting, scenario planning, and decision memos."], ["Responsible adoption", "Define governance, human review, metrics, and a 30-day implementation plan."]],
        stateTitle: "From isolated prompts to managed AI workflows.", stateCopy: "Leading organizations are moving beyond experimentation toward copilots, enterprise search, workflow automation, and governed agents. Advantage comes from process redesign and adoption - not tool access alone.", statePoints: ["Generative AI is becoming embedded in productivity and enterprise platforms.", "Agentic workflows can coordinate multi-step work, but require permissions, monitoring, and stop points.", "Managers remain accountable for evidence quality, data protection, workforce impact, and decisions."],
        sessions: [
          ["The AI-enabled organization", "Map the current state of business AI, distinguish copilots from agents, and identify high-value use cases.", ["AI capability and market landscape", "Opportunity scoring: value, effort, data, risk", "Governance, privacy, and change-readiness"], "Create an AI opportunity portfolio for one function and select a priority workflow."],
          ["The manager's daily copilot", "Apply AI to research, synthesis, communication, meetings, and decision preparation without outsourcing judgment.", ["Executive briefs and decision memos", "Meeting agendas, minutes, actions, and follow-up", "Scenario analysis and assumption testing"], "Build a reusable management prompt and template library for a weekly operating rhythm."],
          ["Automation and operating design", "Turn a recurring process into a controlled automation with triggers, data, approvals, and exception handling.", ["Workflow mapping and bottleneck analysis", "No-code automation and enterprise connectors", "Quality controls, audit trails, and human escalation"], "Prototype one end-to-end workflow such as weekly reporting, issue triage, or competitor monitoring."],
          ["Adoption, ROI, and leadership", "Test the workflow, quantify value, plan adoption, and present an implementation case to decision-makers.", ["Baseline and benefit measurement", "Role redesign, training, and communication", "Risk register and 30-day rollout plan"], "Finalize and pitch an AI management operating system for a real business process."]
        ],
        tools: [["ChatGPT / Claude", "Research, synthesis, reasoning, and management deliverables."], ["Microsoft Copilot / Gemini", "AI inside documents, email, meetings, and office workflows."], ["Perplexity", "Source-linked market and competitor research."], ["Notion AI", "Team knowledge, documentation, and operating playbooks."], ["Zapier / Make", "No-code workflow automation and system handoffs."], ["Miro", "Process mapping, opportunity design, and team alignment."]],
        capstoneTitle: "AI-enabled management operating system", capstoneCopy: "Redesign one recurring management process - from intake to decision and follow-through - and demonstrate how AI improves speed or quality while preserving human accountability.", capstone: ["Current-state and future-state workflow", "Working prototype or guided demonstration", "Controls, risks, and human approval points", "ROI estimate and 30-day adoption plan"]
      },
      hy: {
        title: "ԱԲ-ը բիզնեսում և կառավարման մեջ", audience: "Կառավարիչների, թիմերի ղեկավարների, MBA և բիզնեսի ուսանողների համար", summary: "Կիրառեք ԱԲ-ը որոշումների որակը բարձրացնելու, գործառույթները վերանախագծելու և չափելի բիզնես արժեքով ու պատասխանատու վերահսկմամբ ներդրումը ղեկավարելու համար։", outcome: "Իրական թիմի կամ բիզնես գործընթացի համար ստեղծեք ԱԲ-ով ուժեղացված կառավարման համակարգ՝ հստակ մարդկային հաստատումներով և արդյունավետության չափիչներով։",
        outcomes: [["Ռազմավարական դատողություն", "Գնահատեք ԱԲ հնարավորությունները՝ ըստ արժեքի, իրագործելիության, ռիսկի և կազմակերպական պատրաստվածության։"], ["Կառավարման գործընթացներ", "Բարելավեք հետազոտությունը, հանդիպումների նախապատրաստումը, հաշվետվությունները, սցենարային պլանավորումն ու որոշումների հուշագրերը։"], ["Պատասխանատու ներդրում", "Սահմանեք կառավարում, մարդկային ստուգում, չափիչներ և 30-օրյա իրականացման պլան։"]],
        stateTitle: "Առանձին հարցումներից դեպի կառավարվող ԱԲ գործընթացներ։", stateCopy: "Առաջատար կազմակերպությունները փորձարկումներից անցնում են համաօգնականների, կազմակերպական որոնման, գործընթացների ավտոմատացման և վերահսկվող գործակալների։ Առավելությունը գալիս է գործընթացների վերանախագծումից և ընդունումից, ոչ միայն գործիքների հասանելիությունից։", statePoints: ["Գեներատիվ ԱԲ-ը ներդրվում է արտադրողականության և կազմակերպական հարթակներում։", "Գործակալային գործընթացները կարող են համակարգել բազմաքայլ աշխատանք, սակայն պահանջում են թույլտվություններ, մշտադիտարկում և դադարեցման կետեր։", "Կառավարիչները շարունակում են պատասխանատու լինել ապացույցների որակի, տվյալների պաշտպանության, աշխատուժի ազդեցության և որոշումների համար։"],
        sessions: [
          ["ԱԲ-ով ուժեղացված կազմակերպություն", "Քարտեզագրեք բիզնես ԱԲ-ի ներկա վիճակը, տարբերակեք համաօգնականներն ու գործակալները և բացահայտեք բարձրարժեք կիրառումները։", ["ԱԲ կարողությունների և շուկայի պատկերը", "Հնարավորությունների գնահատում՝ արժեք, ջանք, տվյալներ, ռիսկ", "Կառավարում, գաղտնիություն և փոփոխության պատրաստվածություն"], "Կազմեք մեկ գործառույթի ԱԲ հնարավորությունների պորտֆել և ընտրեք առաջնային գործընթացը։"],
          ["Կառավարչի ամենօրյա համաօգնականը", "Կիրառեք ԱԲ-ը հետազոտության, ամփոփման, հաղորդակցության, հանդիպումների և որոշումների նախապատրաստման մեջ՝ չփոխարինելով մարդկային դատողությունը։", ["Ղեկավար ամփոփագրեր և որոշումների հուշագրեր", "Հանդիպումների օրակարգ, արձանագրություն, գործողություններ և հետադարձ կապ", "Սցենարային վերլուծություն և ենթադրությունների ստուգում"], "Ստեղծեք շաբաթական կառավարման ռիթմի համար բազմակի օգտագործման հարցումների և ձևանմուշների գրադարան։"],
          ["Ավտոմատացում և գործառնական նախագծում", "Կրկնվող գործընթացը վերածեք վերահսկվող ավտոմատացման՝ ազդակներով, տվյալներով, հաստատումներով և բացառությունների մշակմամբ։", ["Գործընթացների քարտեզագրում և խոչընդոտների վերլուծություն", "Առանց կոդի ավտոմատացում և համակարգերի միացումներ", "Որակի վերահսկում, աուդիտի հետք և մարդկային միջամտություն"], "Ստեղծեք շաբաթական հաշվետվության, խնդիրների դասակարգման կամ մրցակիցների մշտադիտարկման ամբողջական նախատիպ։"],
          ["Ներդրում, եկամտաբերություն և առաջնորդություն", "Փորձարկեք գործընթացը, չափեք արժեքը, պլանավորեք ներդրումը և ներկայացրեք իրականացման հիմնավորումը որոշում կայացնողներին։", ["Ելակետային և օգուտների չափում", "Դերերի վերանախագծում, ուսուցում և հաղորդակցություն", "Ռիսկերի գրանցամատյան և 30-օրյա ներդրման պլան"], "Ավարտեք և ներկայացրեք իրական բիզնես գործընթացի ԱԲ կառավարման համակարգը։"]
        ],
        tools: [["ChatGPT / Claude", "Հետազոտություն, ամփոփում, դատողություն և կառավարչական նյութեր։"], ["Microsoft Copilot / Gemini", "ԱԲ փաստաթղթերում, էլ. փոստում, հանդիպումներում և գրասենյակային գործընթացներում։"], ["Perplexity", "Աղբյուրներով շուկայի և մրցակիցների հետազոտություն։"], ["Notion AI", "Թիմային գիտելիք, փաստաթղթավորում և գործառնական ուղեցույցներ։"], ["Zapier / Make", "Առանց կոդի ավտոմատացում և համակարգերի փոխանցումներ։"], ["Miro", "Գործընթացների քարտեզագրում, հնարավորությունների նախագծում և թիմային համաձայնեցում։"]],
        capstoneTitle: "ԱԲ-ով ուժեղացված կառավարման համակարգ", capstoneCopy: "Վերանախագծեք մեկ կրկնվող կառավարչական գործընթաց՝ մուտքից մինչև որոշում և հետագա գործողություն, և ցույց տվեք, թե ինչպես է ԱԲ-ը բարելավում արագությունը կամ որակը՝ պահպանելով մարդկային պատասխանատվությունը։", capstone: ["Ներկա և ապագա գործընթացների քարտեզ", "Աշխատող նախատիպ կամ ուղղորդված ցուցադրություն", "Վերահսկումներ, ռիսկեր և մարդկային հաստատման կետեր", "Եկամտաբերության գնահատում և 30-օրյա ներդրման պլան"]
      }
    },

    "marketing-sales": {
      en: {
        title: "AI in Marketing & Sales", audience: "For marketers, sales teams, entrepreneurs, and business students", summary: "Use AI to understand markets, create stronger messages, personalize outreach, and automate revenue work without sacrificing brand trust.", outcome: "Design a campaign-to-conversation workflow that turns customer evidence into targeted content, qualified outreach, and measurable follow-up.",
        outcomes: [["Market intelligence", "Synthesize customer, competitor, search, and campaign signals into actionable insight."], ["Content and selling", "Create on-brand content, offers, account research, and personalized outreach with human editing."], ["Revenue automation", "Connect lead capture, qualification, follow-up, CRM updates, and reporting with safeguards."]],
        stateTitle: "AI is reshaping the full revenue journey.", stateCopy: "The state of practice combines multimodal content, conversational discovery, predictive scoring, sales copilots, and automated lifecycle journeys. Winning teams connect these capabilities to differentiated strategy and first-party customer evidence.", statePoints: ["Search and discovery are shifting toward answer engines and conversational interfaces.", "Synthetic content increases volume; distinctive positioning and editorial judgment create value.", "Personalization must respect consent, data quality, platform rules, and brand reputation."],
        sessions: [
          ["Market, customer, and channel intelligence", "Explore the latest marketing and sales AI landscape and turn fragmented signals into a focused opportunity map.", ["Customer and competitor research", "Social, search, review, and CRM signal synthesis", "Positioning, segmentation, and evidence quality"], "Build an evidence-backed ideal customer profile and messaging hypothesis."],
          ["Daily content and sales workflows", "Create briefs, campaigns, sales assets, and outreach that stay specific, on-brand, and reviewable.", ["Brand-aware prompting and content systems", "Offer, email, social, landing-page, and sales-deck workflows", "Account research and outreach personalization"], "Produce a coordinated mini-campaign and three-stage outreach sequence."],
          ["Revenue automation", "Design a controlled journey from lead capture to qualification, nurture, CRM update, and performance reporting.", ["Lead enrichment and scoring", "Workflow triggers, CRM hygiene, and follow-up", "Consent, disclosure, deliverability, and quality assurance"], "Prototype a lead-to-follow-up automation with a human approval gate."],
          ["Experimentation and growth review", "Launch a measurable test, interpret results, and package the complete revenue workflow for stakeholder approval.", ["Experiment design and channel metrics", "Attribution limits and decision dashboards", "Campaign review, learning loop, and scale plan"], "Present a campaign-to-conversation system with assets, automation, and KPI plan."]
        ],
        tools: [["ChatGPT / Claude", "Strategy, briefs, messaging, drafts, and sales enablement."], ["Perplexity", "Customer, category, and competitor research with sources."], ["Canva / Adobe Firefly", "Brand-controlled visual content and campaign variants."], ["HubSpot AI", "CRM, lifecycle communication, lead context, and reporting."], ["Apollo / LinkedIn Sales Navigator", "Prospecting, account intelligence, and outreach preparation."], ["Zapier / Make", "Lead routing, follow-up, alerts, and reporting automation."]],
        capstoneTitle: "Campaign-to-conversation growth engine", capstoneCopy: "Create a small but complete revenue system for one offer: evidence-based audience definition, differentiated message, content set, personalized outreach, automation map, and measurement plan.", capstone: ["ICP, customer insight, and positioning brief", "Coordinated campaign and sales assets", "Lead qualification and follow-up automation", "Experiment dashboard and optimization plan"]
      },
      hy: {
        title: "ԱԲ-ը մարքեթինգում և վաճառքում", audience: "Մարքեթոլոգների, վաճառքի թիմերի, ձեռնարկատերերի և բիզնեսի ուսանողների համար", summary: "Կիրառեք ԱԲ-ը շուկան հասկանալու, ավելի ուժեղ հաղորդագրություններ ստեղծելու, անհատականացված կապ հաստատելու և եկամտային աշխատանքն ավտոմատացնելու համար՝ չվնասելով բրենդի վստահությանը։", outcome: "Նախագծեք արշավից դեպի զրույց ամբողջական գործընթաց, որը հաճախորդների տվյալները վերածում է թիրախավորված բովանդակության, որակավորված կապերի և չափելի շարունակության։",
        outcomes: [["Շուկայի հետախուզություն", "Հաճախորդների, մրցակիցների, որոնման և արշավների ազդակները վերածեք կիրառելի պատկերացումների։"], ["Բովանդակություն և վաճառք", "Ստեղծեք բրենդին համապատասխան բովանդակություն, առաջարկներ, հաճախորդների հետազոտություն և անհատականացված հաղորդագրություններ՝ մարդկային խմբագրմամբ։"], ["Եկամտային ավտոմատացում", "Միացրեք լիդերի հավաքումը, որակավորումը, հետադարձ կապը, CRM թարմացումները և հաշվետվությունը՝ պաշտպանիչ միջոցներով։"]],
        stateTitle: "ԱԲ-ը վերաձևավորում է եկամտի ամբողջ ճանապարհը։", stateCopy: "Արդի փորձը համատեղում է բազմամոդալ բովանդակությունը, զրույցային որոնումը, կանխատեսող գնահատումը, վաճառքի համաօգնականները և հաճախորդի կյանքի ցիկլի ավտոմատացումը։ Հաջող թիմերն այս հնարավորությունները կապում են տարբերակված ռազմավարության ու սեփական հաճախորդային տվյալների հետ։", statePoints: ["Որոնումն ու բացահայտումը շարժվում են դեպի պատասխանների համակարգեր և զրույցային միջերեսներ։", "Սինթետիկ բովանդակությունն ավելացնում է ծավալը, իսկ հստակ դիրքավորումն ու խմբագրական դատողությունը՝ արժեքը։", "Անհատականացումը պետք է պահպանի համաձայնությունը, տվյալների որակը, հարթակների կանոններն ու բրենդի հեղինակությունը։"],
        sessions: [
          ["Շուկայի, հաճախորդի և ալիքների հետախուզություն", "Ուսումնասիրեք մարքեթինգի ու վաճառքի ԱԲ արդի միջավայրը և մասնատված ազդակները վերածեք հնարավորությունների քարտեզի։", ["Հաճախորդների և մրցակիցների հետազոտություն", "Սոցիալական, որոնման, կարծիքների և CRM ազդակների ամփոփում", "Դիրքավորում, բաժանում և ապացույցների որակ"], "Ստեղծեք ապացույցներով հիմնավորված իդեալական հաճախորդի նկարագիր և հաղորդագրության վարկած։"],
          ["Բովանդակության և վաճառքի ամենօրյա գործընթացներ", "Ստեղծեք հստակ, բրենդին համապատասխան և ստուգելի ամփոփագրեր, արշավներ, վաճառքի նյութեր ու հաղորդագրություններ։", ["Բրենդային հարցումներ և բովանդակության համակարգեր", "Առաջարկի, էլ. նամակի, սոցիալական նյութի, էջի և վաճառքի ներկայացման գործընթացներ", "Հաշվի հետազոտություն և հաղորդագրությունների անհատականացում"], "Պատրաստեք համակարգված փոքր արշավ և եռաստիճան կապի հաջորդականություն։"],
          ["Եկամտային ավտոմատացում", "Նախագծեք վերահսկվող ճանապարհ՝ լիդի հավաքումից մինչև որակավորում, զարգացում, CRM թարմացում և արդյունքների հաշվետվություն։", ["Լիդերի հարստացում և գնահատում", "Ազդակներ, CRM կարգապահություն և հետադարձ կապ", "Համաձայնություն, բացահայտում, առաքելիություն և որակի ապահովում"], "Ստեղծեք լիդից մինչև հետադարձ կապ ավտոմատացման նախատիպ՝ մարդկային հաստատման փուլով։"],
          ["Փորձարկում և աճի վերանայում", "Մեկնարկեք չափելի փորձ, մեկնաբանեք արդյունքները և ամբողջ եկամտային գործընթացը ներկայացրեք հաստատման։", ["Փորձարկման նախագծում և ալիքների չափիչներ", "Վերագրման սահմանափակումներ և որոշումների վահանակներ", "Արշավի վերանայում, ուսուցման շրջան և ընդլայնման պլան"], "Ներկայացրեք արշավից դեպի զրույց համակարգ՝ նյութերով, ավտոմատացմամբ և չափիչների պլանով։"]
        ],
        tools: [["ChatGPT / Claude", "Ռազմավարություն, ամփոփագրեր, հաղորդագրություններ, սևագրեր և վաճառքի աջակցություն։"], ["Perplexity", "Հաճախորդի, շուկայի և մրցակիցների աղբյուրներով հետազոտություն։"], ["Canva / Adobe Firefly", "Բրենդով վերահսկվող տեսողական բովանդակություն և տարբերակներ։"], ["HubSpot AI", "CRM, կյանքի ցիկլի հաղորդակցություն, լիդերի համատեքստ և հաշվետվություն։"], ["Apollo / LinkedIn Sales Navigator", "Հեռանկարային հաճախորդների որոնում, հաշվի հետախուզություն և կապի նախապատրաստում։"], ["Zapier / Make", "Լիդերի ուղղորդում, հետադարձ կապ, ծանուցումներ և հաշվետվությունների ավտոմատացում։"]],
        capstoneTitle: "Արշավից դեպի զրույց աճի համակարգ", capstoneCopy: "Ստեղծեք մեկ առաջարկի փոքր, բայց ամբողջական եկամտային համակարգ՝ ապացույցներով լսարանի սահմանում, տարբերակված հաղորդագրություն, բովանդակության հավաքածու, անհատականացված կապ, ավտոմատացման քարտեզ և չափման պլան։", capstone: ["Իդեալական հաճախորդի, պատկերացումների և դիրքավորման ամփոփագիր", "Համակարգված արշավի և վաճառքի նյութեր", "Լիդերի որակավորում և հետադարձ կապի ավտոմատացում", "Փորձարկման վահանակ և օպտիմալացման պլան"]
      }
    },

    "finance-accounting": {
      en: {
        title: "AI in Finance & Accounting", audience: "For finance, accounting, banking, and economics professionals", summary: "Apply AI to analysis, close, reporting, controls, and decision support while protecting accuracy, confidentiality, and auditability.", outcome: "Build a controlled finance workflow that transforms source data into analysis, review evidence, and a decision-ready management output.",
        outcomes: [["Faster analysis", "Clean, reconcile, investigate, and explain financial data with reproducible steps."], ["Reliable reporting", "Draft variance narratives, forecasts, management packs, and control documentation."], ["Governed automation", "Design approvals, validation, access boundaries, and audit evidence around AI-supported work."]],
        stateTitle: "Finance AI is moving from drafting to controlled execution.", stateCopy: "Modern finance teams combine spreadsheet copilots, document intelligence, anomaly detection, forecasting, and close automation. High-value adoption depends on traceable calculations and separation between generation, review, and approval.", statePoints: ["AI can accelerate unstructured-document extraction and narrative reporting.", "Predictive models and copilots support forecasts, but assumptions and data lineage must remain visible.", "Confidentiality, segregation of duties, model risk, and audit evidence are non-negotiable."],
        sessions: [
          ["Finance AI landscape and controls", "Assess current capabilities across accounting, FP&A, banking, audit, and risk, then select safe, valuable use cases.", ["Document AI, copilots, forecasting, and anomaly detection", "Materiality, confidentiality, and model risk", "Data lineage and control design"], "Score finance use cases and build a control checklist for one priority process."],
          ["Daily analysis and reporting", "Use AI with spreadsheets and documents to investigate data, draft explanations, and improve management reporting.", ["Data cleaning, classification, and reconciliation", "Variance analysis and driver trees", "Management narratives and executive summaries"], "Produce a reviewed variance pack with calculations, evidence, and bounded commentary."],
          ["Close and finance automation", "Map and prototype a controlled workflow for recurring finance operations and exception handling.", ["Invoice and document extraction", "Close checklist, journal support, and reconciliations", "Triggers, approvals, exception queues, and audit logs"], "Prototype one automation such as invoice triage, account reconciliation, or weekly cash reporting."],
          ["Forecast, challenge, and communicate", "Create a decision-ready model, pressure-test assumptions, and present conclusions with limitations.", ["Scenario and sensitivity analysis", "Forecast challenge and anomaly review", "Governance memo and stakeholder communication"], "Deliver a controlled analysis workflow and decision pack for a real finance question."]
        ],
        tools: [["Excel Copilot / Gemini in Sheets", "Formula support, analysis, summaries, and structured review."], ["ChatGPT / Claude", "Narratives, control thinking, document review, and scenario framing."], ["Power BI", "Repeatable models, dashboards, and decision reporting."], ["Power Query", "Traceable data preparation and recurring transformations."], ["UiPath / Power Automate", "Controlled task automation and approvals."], ["Azure AI Document Intelligence", "Structured extraction from invoices and financial documents."]],
        capstoneTitle: "Controlled finance intelligence workflow", capstoneCopy: "Transform a recurring finance task into a documented workflow that produces analysis and a decision-ready output while preserving source traceability, review, approval, and audit evidence.", capstone: ["Source-to-output process and data lineage", "Validated analysis or automation prototype", "Control matrix and exception handling", "Management pack with recommendation and limitations"]
      },
      hy: {
        title: "ԱԲ-ը ֆինանսներում և հաշվապահությունում", audience: "Ֆինանսների, հաշվապահության, բանկային և տնտեսագիտական ոլորտների մասնագետների համար", summary: "Կիրառեք ԱԲ-ը վերլուծության, փակման, հաշվետվությունների, վերահսկման և որոշումների աջակցության մեջ՝ պաշտպանելով ճշգրտությունը, գաղտնիությունն ու աուդիտի հնարավորությունը։", outcome: "Ստեղծեք վերահսկվող ֆինանսական գործընթաց, որը սկզբնաղբյուր տվյալները վերածում է վերլուծության, ստուգման ապացույցների և որոշման համար պատրաստ կառավարչական արդյունքի։",
        outcomes: [["Ավելի արագ վերլուծություն", "Մաքրեք, համադրեք, ուսումնասիրեք և բացատրեք ֆինանսական տվյալները վերարտադրելի քայլերով։"], ["Հուսալի հաշվետվություն", "Պատրաստեք շեղումների մեկնաբանություններ, կանխատեսումներ, կառավարչական փաթեթներ և վերահսկման փաստաթղթեր։"], ["Կառավարվող ավտոմատացում", "Նախագծեք հաստատումներ, վավերացում, հասանելիության սահմաններ և աուդիտի ապացույցներ ԱԲ-ով աշխատանքի շուրջ։"]],
        stateTitle: "Ֆինանսական ԱԲ-ը սևագրումից անցնում է վերահսկվող իրականացման։", stateCopy: "Ժամանակակից ֆինանսական թիմերը համատեղում են աղյուսակների համաօգնականները, փաստաթղթերի վերլուծությունը, անոմալիաների հայտնաբերումը, կանխատեսումն ու փակման ավտոմատացումը։ Բարձրարժեք ներդրումը պահանջում է հետագծելի հաշվարկներ և տարանջատում ստեղծման, ստուգման ու հաստատման միջև։", statePoints: ["ԱԲ-ը կարող է արագացնել չկառուցված փաստաթղթերից տվյալների հանումը և պատմողական հաշվետվությունը։", "Կանխատեսող մոդելներն ու համաօգնականներն աջակցում են կանխատեսմանը, սակայն ենթադրություններն ու տվյալների ծագումը պետք է տեսանելի մնան։", "Գաղտնիությունը, պարտականությունների տարանջատումը, մոդելի ռիսկը և աուդիտի ապացույցները պարտադիր են։"],
        sessions: [
          ["Ֆինանսական ԱԲ միջավայր և վերահսկումներ", "Գնահատեք հաշվապահության, FP&A-ի, բանկային, աուդիտի և ռիսկերի արդի հնարավորությունները, ապա ընտրեք անվտանգ ու արժեքավոր կիրառումներ։", ["Փաստաթղթային ԱԲ, համաօգնականներ, կանխատեսում և անոմալիաների հայտնաբերում", "Էականություն, գաղտնիություն և մոդելի ռիսկ", "Տվյալների ծագում և վերահսկման նախագծում"], "Գնահատեք ֆինանսական կիրառումները և մեկ առաջնային գործընթացի համար կազմեք վերահսկման ստուգաթերթ։"],
          ["Ամենօրյա վերլուծություն և հաշվետվություն", "ԱԲ-ը կիրառեք աղյուսակների ու փաստաթղթերի հետ՝ տվյալներն ուսումնասիրելու, բացատրություններ պատրաստելու և կառավարչական հաշվետվությունը բարելավելու համար։", ["Տվյալների մաքրում, դասակարգում և համադրում", "Շեղումների վերլուծություն և գործոնների ծառ", "Կառավարչական մեկնաբանություններ և ղեկավար ամփոփագրեր"], "Պատրաստեք ստուգված շեղումների փաթեթ՝ հաշվարկներով, ապացույցներով և սահմանափակված մեկնաբանությամբ։"],
          ["Փակում և ֆինանսական ավտոմատացում", "Քարտեզագրեք և նախատիպեք կրկնվող ֆինանսական գործողությունների ու բացառությունների մշակման վերահսկվող գործընթաց։", ["Հաշիվ-ապրանքագրերի և փաստաթղթերի տվյալահանում", "Փակման ստուգաթերթ, գրանցումների աջակցություն և համադրումներ", "Ազդակներ, հաստատումներ, բացառությունների հերթ և աուդիտի գրանցումներ"], "Ստեղծեք հաշիվների դասակարգման, հաշիվների համադրման կամ շաբաթական դրամական հաշվետվության ավտոմատացման նախատիպ։"],
          ["Կանխատեսել, վիճարկել և հաղորդակցվել", "Ստեղծեք որոշման համար պատրաստ մոդել, փորձարկեք ենթադրությունները և ներկայացրեք եզրակացությունները սահմանափակումներով։", ["Սցենարային և զգայունության վերլուծություն", "Կանխատեսման քննադատական ստուգում և անոմալիաների վերանայում", "Կառավարման հուշագիր և շահակիցների հաղորդակցություն"], "Ներկայացրեք իրական ֆինանսական հարցի վերահսկվող վերլուծական գործընթաց և որոշումների փաթեթ։"]
        ],
        tools: [["Excel Copilot / Gemini in Sheets", "Բանաձևերի աջակցություն, վերլուծություն, ամփոփում և կառուցվածքային ստուգում։"], ["ChatGPT / Claude", "Մեկնաբանություններ, վերահսկման մտածողություն, փաստաթղթերի ստուգում և սցենարների ձևակերպում։"], ["Power BI", "Վերարտադրելի մոդելներ, վահանակներ և որոշումների հաշվետվություն։"], ["Power Query", "Հետագծելի տվյալների պատրաստում և կրկնվող փոխակերպումներ։"], ["UiPath / Power Automate", "Վերահսկվող առաջադրանքների ավտոմատացում և հաստատումներ։"], ["Azure AI Document Intelligence", "Հաշիվներից և ֆինանսական փաստաթղթերից կառուցվածքային տվյալահանում։"]],
        capstoneTitle: "Վերահսկվող ֆինանսական հետախուզության գործընթաց", capstoneCopy: "Կրկնվող ֆինանսական առաջադրանքը վերածեք փաստագրված գործընթացի, որը ստեղծում է վերլուծություն և որոշման համար պատրաստ արդյունք՝ պահպանելով աղբյուրների հետագծելիությունը, ստուգումը, հաստատումն ու աուդիտի ապացույցները։", capstone: ["Աղբյուրից արդյունք գործընթաց և տվյալների ծագում", "Վավերացված վերլուծություն կամ ավտոմատացման նախատիպ", "Վերահսկման մատրից և բացառությունների մշակում", "Կառավարչական փաթեթ՝ առաջարկությամբ և սահմանափակումներով"]
      }
    },

    "product-project": {
      en: {
        title: "AI for Product & Project Management", audience: "For product managers, project managers, and IT/business students", summary: "Use AI across discovery, requirements, planning, delivery, risk, and stakeholder communication while keeping product judgment and ownership human.", outcome: "Build an AI-supported delivery system for a real initiative, from evidence and requirements through planning, risk monitoring, and stakeholder reporting.",
        outcomes: [["Evidence-led discovery", "Synthesize research, feedback, and usage signals into problems and opportunities."], ["Stronger delivery", "Draft requirements, plans, tests, risks, and communications with structured review."], ["Workflow visibility", "Automate status collection, issue triage, meeting actions, and stakeholder updates."]],
        stateTitle: "AI is becoming part of the product delivery stack.", stateCopy: "Product and project teams now use AI for research synthesis, prototyping, requirements, estimation support, knowledge retrieval, and delivery reporting. The strongest practice treats generated work as a hypothesis to validate - not a substitute for discovery or accountability.", statePoints: ["Multimodal models can interpret interviews, screenshots, documents, and prototypes together.", "AI-native prototyping shortens feedback cycles but can hide technical and user-risk assumptions.", "Project agents can monitor work and prepare actions, yet scope, priority, and acceptance remain human decisions."],
        sessions: [
          ["AI across the delivery lifecycle", "Map current product and project advances, identify suitable use cases, and set evidence and governance rules.", ["Discovery, planning, prototyping, and delivery copilots", "Use-case scoring and workflow boundaries", "Data, IP, security, and accountability"], "Create an opportunity map for one product or project lifecycle."],
          ["Daily product and project work", "Accelerate research synthesis, requirements, plans, risk work, and stakeholder communication.", ["Interview and feedback synthesis", "PRDs, user stories, acceptance criteria, and test scenarios", "Plans, RAID logs, decisions, and status updates"], "Produce a reviewed delivery pack for one defined initiative."],
          ["Automation and delivery intelligence", "Design a workflow that gathers signals, detects exceptions, and prepares action without silently changing commitments.", ["Meeting-to-action and issue-triage workflows", "Portfolio and dependency summaries", "Human approvals, access, and escalation"], "Prototype an automated delivery pulse from project inputs to stakeholder update."],
          ["Prototype, validate, and present", "Use AI-assisted prototyping to test assumptions, then create a credible execution and measurement plan.", ["Rapid prototype and usability scenario", "Prioritization and success metrics", "Roadmap trade-offs and executive narrative"], "Present an AI-supported delivery system with evidence, prototype, plan, and controls."]
        ],
        tools: [["ChatGPT / Claude", "Research synthesis, requirements, risks, and decision support."], ["Notion AI / Confluence AI", "Product knowledge, specifications, and team documentation."], ["Jira AI / Asana Intelligence", "Issue summaries, planning support, and delivery signals."], ["Figma AI", "Concept exploration, UI drafts, and prototype acceleration."], ["Miro AI", "Discovery mapping, workshops, and prioritization."], ["Zapier / Make", "Project updates, alerts, handoffs, and reporting workflows."]],
        capstoneTitle: "AI-supported product delivery system", capstoneCopy: "Create a connected workflow for one initiative that turns evidence into requirements, a prototype or delivery plan, monitored risks, and a decision-ready stakeholder update.", capstone: ["Discovery evidence and problem framing", "Reviewed requirements and delivery plan", "Prototype or delivery-intelligence automation", "Success metrics, risks, and stakeholder narrative"]
      },
      hy: {
        title: "ԱԲ-ը պրոդուկտների և նախագծերի կառավարման մեջ", audience: "Պրոդուկտ և նախագծերի ղեկավարների, ՏՏ ու բիզնեսի ուսանողների համար", summary: "Կիրառեք ԱԲ-ը բացահայտման, պահանջների, պլանավորման, իրականացման, ռիսկերի և շահակիցների հաղորդակցության մեջ՝ պահպանելով մարդկային դատողությունն ու պատասխանատվությունը։", outcome: "Իրական նախաձեռնության համար ստեղծեք ԱԲ-ով աջակցվող իրականացման համակարգ՝ ապացույցներից ու պահանջներից մինչև պլանավորում, ռիսկերի մշտադիտարկում և շահակիցների հաշվետվություն։",
        outcomes: [["Ապացույցներով բացահայտում", "Հետազոտությունը, արձագանքն ու օգտագործման ազդակները վերածեք խնդիրների և հնարավորությունների։"], ["Ավելի ուժեղ իրականացում", "Կառուցվածքային ստուգմամբ պատրաստեք պահանջներ, պլաններ, թեստեր, ռիսկեր և հաղորդակցություն։"], ["Գործընթացի տեսանելիություն", "Ավտոմատացրեք կարգավիճակի հավաքումը, խնդիրների դասակարգումը, հանդիպումների գործողություններն ու շահակիցների թարմացումները։"]],
        stateTitle: "ԱԲ-ը դառնում է պրոդուկտի իրականացման գործիքակազմի մաս։", stateCopy: "Պրոդուկտ և նախագծային թիմերն ԱԲ-ը կիրառում են հետազոտության ամփոփման, նախատիպերի, պահանջների, գնահատման աջակցության, գիտելիքի որոնման և իրականացման հաշվետվության համար։ Լավագույն փորձը ստեղծված արդյունքը դիտարկում է որպես ստուգման ենթակա վարկած, ոչ թե բացահայտման կամ պատասխանատվության փոխարինում։", statePoints: ["Բազմամոդալ մոդելները կարող են միասին մեկնաբանել հարցազրույցներ, պատկերներ, փաստաթղթեր և նախատիպեր։", "ԱԲ-ով նախատիպավորումն արագացնում է արձագանքի շրջանը, բայց կարող է թաքցնել տեխնիկական և օգտագործողի ռիսկերի ենթադրությունները։", "Նախագծային գործակալները կարող են հետևել աշխատանքին և պատրաստել գործողություններ, սակայն շրջանակը, առաջնահերթությունն ու ընդունումը մնում են մարդկային որոշումներ։"],
        sessions: [
          ["ԱԲ-ը իրականացման ամբողջ ցիկլում", "Քարտեզագրեք պրոդուկտի և նախագծի արդի առաջընթացը, ընտրեք կիրառումները և սահմանեք ապացույցների ու կառավարման կանոնները։", ["Բացահայտման, պլանավորման, նախատիպավորման և իրականացման համաօգնականներ", "Կիրառումների գնահատում և գործընթացի սահմաններ", "Տվյալներ, մտավոր սեփականություն, անվտանգություն և պատասխանատվություն"], "Կազմեք մեկ պրոդուկտի կամ նախագծի կյանքի ցիկլի հնարավորությունների քարտեզ։"],
          ["Պրոդուկտի և նախագծի ամենօրյա աշխատանք", "Արագացրեք հետազոտության ամփոփումը, պահանջները, պլանները, ռիսկերի աշխատանքը և շահակիցների հաղորդակցությունը։", ["Հարցազրույցների և արձագանքների ամփոփում", "PRD, օգտատիրոջ պատմություններ, ընդունման չափանիշներ և թեստային սցենարներ", "Պլաններ, RAID գրանցումներ, որոշումներ և կարգավիճակի թարմացումներ"], "Պատրաստեք մեկ նախաձեռնության ստուգված իրականացման փաթեթ։"],
          ["Ավտոմատացում և իրականացման հետախուզություն", "Նախագծեք գործընթաց, որը հավաքում է ազդակները, հայտնաբերում բացառությունները և պատրաստում գործողություններ՝ առանց պարտավորություններն ինքնուրույն փոխելու։", ["Հանդիպումից գործողություն և խնդիրների դասակարգում", "Պորտֆելի և կախվածությունների ամփոփումներ", "Մարդկային հաստատումներ, հասանելիություն և սրում"], "Ստեղծեք նախագծային մուտքերից շահակիցների թարմացում ստացող ավտոմատացված զարկերակի նախատիպ։"],
          ["Նախատիպ, վավերացում և ներկայացում", "ԱԲ-ով արագ նախատիպով ստուգեք ենթադրությունները, ապա կազմեք իրատեսական իրականացման ու չափման պլան։", ["Արագ նախատիպ և օգտագործելիության սցենար", "Առաջնահերթություն և հաջողության չափիչներ", "Ճանապարհային քարտեզի փոխզիջումներ և ղեկավար պատմություն"], "Ներկայացրեք ԱԲ-ով աջակցվող իրականացման համակարգ՝ ապացույցներով, նախատիպով, պլանով և վերահսկումներով։"]
        ],
        tools: [["ChatGPT / Claude", "Հետազոտության ամփոփում, պահանջներ, ռիսկեր և որոշումների աջակցություն։"], ["Notion AI / Confluence AI", "Պրոդուկտի գիտելիք, բնութագրեր և թիմային փաստաթղթավորում։"], ["Jira AI / Asana Intelligence", "Խնդիրների ամփոփում, պլանավորման աջակցություն և իրականացման ազդակներ։"], ["Figma AI", "Գաղափարների ուսումնասիրություն, միջերեսների սևագրեր և նախատիպավորման արագացում։"], ["Miro AI", "Բացահայտման քարտեզներ, աշխատաժողովներ և առաջնահերթություն։"], ["Zapier / Make", "Նախագծի թարմացումներ, ծանուցումներ, փոխանցումներ և հաշվետվության գործընթացներ։"]],
        capstoneTitle: "ԱԲ-ով աջակցվող պրոդուկտի իրականացման համակարգ", capstoneCopy: "Մեկ նախաձեռնության համար ստեղծեք կապակցված գործընթաց, որը ապացույցները վերածում է պահանջների, նախատիպի կամ իրականացման պլանի, վերահսկվող ռիսկերի և որոշման համար պատրաստ շահակիցների թարմացման։", capstone: ["Բացահայտման ապացույցներ և խնդրի ձևակերպում", "Ստուգված պահանջներ և իրականացման պլան", "Նախատիպ կամ իրականացման հետախուզության ավտոմատացում", "Հաջողության չափիչներ, ռիսկեր և շահակիցների պատմություն"]
      }
    },

    "data-decisions": {
      en: {
        title: "AI for Data Analysis & Decision Making", audience: "For professionals across business, public service, research, and operations", summary: "Turn messy data into trustworthy analysis, clear visual evidence, and decisions that state assumptions, uncertainty, and limitations.", outcome: "Build a reproducible decision brief that moves from raw data through validation and analysis to a defensible recommendation and monitoring plan.",
        outcomes: [["Data readiness", "Profile, clean, structure, and document data before drawing conclusions."], ["AI-assisted analysis", "Use natural-language and code-based tools to explore patterns, test questions, and visualize evidence."], ["Decision quality", "Separate signal from noise and communicate uncertainty, alternatives, and action thresholds."]],
        stateTitle: "Natural-language analytics is widening access - not removing rigor.", stateCopy: "Modern copilots can write formulas and code, query semantic models, generate charts, and explain patterns. The frontier is conversational and agentic analysis, but trustworthy decisions still require validated data, appropriate methods, and reproducible evidence.", statePoints: ["Multimodal models can interpret tables, documents, charts, and images in one analysis.", "Automated insight generation can surface patterns quickly, including misleading ones.", "Decision-makers need provenance, method checks, uncertainty, and clear limits on causal claims."],
        sessions: [
          ["The modern analytics stack", "Understand current advances, frame a decision question, and audit whether available data can support it.", ["Conversational analytics, code copilots, and BI assistants", "Question framing and decision criteria", "Data quality, privacy, bias, and provenance"], "Create a data-readiness report and analysis plan for a realistic decision."],
          ["Daily analysis with AI", "Clean and explore a dataset, write formulas or code, investigate outliers, and create truthful visual evidence.", ["Profiling, cleaning, joining, and categorization", "Descriptive analysis and segment comparison", "Chart selection and visual integrity"], "Produce a reproducible notebook or spreadsheet with a decision-quality chart."],
          ["Automated insight and monitoring", "Design a recurring workflow that refreshes data, checks quality, detects changes, and routes exceptions.", ["Automated data preparation and refresh", "Thresholds, anomaly detection, and alerts", "Human review and false-positive handling"], "Prototype a monitored KPI workflow with a data-quality gate and alert logic."],
          ["Decision brief and challenge", "Test sensitivity, distinguish correlation from causation, and communicate a bounded recommendation.", ["Scenario, sensitivity, and uncertainty", "Alternative explanations and decision traps", "Executive narrative and monitoring plan"], "Present a decision brief with evidence, limitations, recommendation, and next measurement."]
        ],
        tools: [["Excel / Google Sheets AI", "Accessible cleaning, formulas, analysis, and charting."], ["ChatGPT Advanced Data Analysis", "Code-assisted exploration, visualization, and reproducible outputs."], ["Claude", "Large-document and dataset reasoning with structured critique."], ["Power BI / Tableau", "Semantic models, dashboards, and monitored decisions."], ["Python + pandas", "Transparent, repeatable analysis and validation."], ["Power Query / Alteryx", "Repeatable preparation and workflow automation."]],
        capstoneTitle: "Evidence-to-decision intelligence brief", capstoneCopy: "Answer a real organizational question using a documented dataset, reproducible analysis, clear visual evidence, and a recommendation that explicitly communicates assumptions, uncertainty, and monitoring.", capstone: ["Decision question and data-quality assessment", "Reproducible analysis and visual evidence", "Sensitivity, alternatives, and limitations", "Recommendation, action threshold, and monitoring plan"]
      },
      hy: {
        title: "ԱԲ-ը տվյալների վերլուծության և որոշումների կայացման մեջ", audience: "Բիզնեսի, հանրային ծառայության, հետազոտության և գործառույթների տարբեր մասնագետների համար", summary: "Չկարգավորված տվյալները վերածեք վստահելի վերլուծության, հստակ տեսողական ապացույցների և որոշումների, որոնք բացահայտում են ենթադրությունները, անորոշությունն ու սահմանափակումները։", outcome: "Ստեղծեք վերարտադրելի որոշման ամփոփագիր՝ հում տվյալներից, վավերացումից ու վերլուծությունից մինչև պաշտպանելի առաջարկություն և մշտադիտարկման պլան։",
        outcomes: [["Տվյալների պատրաստվածություն", "Ուսումնասիրեք, մաքրեք, կառուցեք և փաստագրեք տվյալները՝ նախքան եզրակացություն անելը։"], ["ԱԲ-ով աջակցվող վերլուծություն", "Բնական լեզվի և կոդի գործիքներով ուսումնասիրեք օրինաչափությունները, ստուգեք հարցերը և պատկերեք ապացույցները։"], ["Որոշման որակ", "Տարբերակեք ազդակը աղմուկից և հաղորդեք անորոշությունը, այլընտրանքներն ու գործողության շեմերը։"]],
        stateTitle: "Բնական լեզվով վերլուծությունն ընդլայնում է հասանելիությունը, բայց չի վերացնում խստությունը։", stateCopy: "Ժամանակակից համաօգնականները կարող են գրել բանաձևեր և կոդ, հարցումներ ուղարկել իմաստային մոդելներին, ստեղծել գծապատկերներ ու բացատրել օրինաչափությունները։ Առաջատար ուղղությունը զրույցային և գործակալային վերլուծությունն է, սակայն վստահելի որոշումները պահանջում են վավերացված տվյալներ, համապատասխան մեթոդներ և վերարտադրելի ապացույցներ։", statePoints: ["Բազմամոդալ մոդելները կարող են մեկ վերլուծության մեջ մեկնաբանել աղյուսակներ, փաստաթղթեր, գծապատկերներ և պատկերներ։", "Ավտոմատ պատկերացումները կարող են արագ բացահայտել օրինաչափություններ, ներառյալ մոլորեցնողները։", "Որոշում կայացնողներին պետք են ծագում, մեթոդի ստուգումներ, անորոշություն և պատճառահետևանքային պնդումների հստակ սահմաններ։"],
        sessions: [
          ["Ժամանակակից վերլուծական գործիքակազմ", "Հասկացեք արդի առաջընթացը, ձևակերպեք որոշման հարցը և ստուգեք՝ արդյոք տվյալները կարող են աջակցել դրան։", ["Զրույցային վերլուծություն, կոդի համաօգնականներ և BI օգնականներ", "Հարցի ձևակերպում և որոշման չափանիշներ", "Տվյալների որակ, գաղտնիություն, կողմնակալություն և ծագում"], "Կազմեք իրական որոշման տվյալների պատրաստվածության հաշվետվություն և վերլուծության պլան։"],
          ["Ամենօրյա վերլուծություն ԱԲ-ով", "Մաքրեք և ուսումնասիրեք տվյալների հավաքածուն, գրեք բանաձև կամ կոդ, ուսումնասիրեք արտառոց արժեքները և ստեղծեք ճշմարիտ տեսողական ապացույց։", ["Պրոֆիլավորում, մաքրում, միացում և դասակարգում", "Նկարագրական վերլուծություն և խմբերի համեմատություն", "Գծապատկերի ընտրություն և տեսողական ազնվություն"], "Ստեղծեք վերարտադրելի աշխատանքային տետր կամ աղյուսակ՝ որոշման որակի գծապատկերով։"],
          ["Ավտոմատ պատկերացում և մշտադիտարկում", "Նախագծեք կրկնվող գործընթաց, որը թարմացնում է տվյալները, ստուգում որակը, հայտնաբերում փոփոխությունները և ուղղորդում բացառությունները։", ["Տվյալների ավտոմատ պատրաստում և թարմացում", "Շեմեր, անոմալիաների հայտնաբերում և ծանուցումներ", "Մարդկային ստուգում և կեղծ ազդակների մշակում"], "Ստեղծեք մշտադիտարկվող KPI գործընթացի նախատիպ՝ տվյալների որակի դարպասով և ազդանշանային տրամաբանությամբ։"],
          ["Որոշման ամփոփագիր և քննադատական ստուգում", "Ստուգեք զգայունությունը, տարբերակեք հարաբերակցությունը պատճառականությունից և հաղորդեք սահմանափակված առաջարկություն։", ["Սցենար, զգայունություն և անորոշություն", "Այլընտրանքային բացատրություններ և որոշման թակարդներ", "Ղեկավար պատմություն և մշտադիտարկման պլան"], "Ներկայացրեք որոշման ամփոփագիր՝ ապացույցներով, սահմանափակումներով, առաջարկությամբ և հաջորդ չափմամբ։"]
        ],
        tools: [["Excel / Google Sheets AI", "Հասանելի մաքրում, բանաձևեր, վերլուծություն և գծապատկերներ։"], ["ChatGPT Advanced Data Analysis", "Կոդով աջակցվող ուսումնասիրություն, պատկերում և վերարտադրելի արդյունքներ։"], ["Claude", "Մեծ փաստաթղթերի և տվյալների վերլուծություն՝ կառուցվածքային քննադատությամբ։"], ["Power BI / Tableau", "Իմաստային մոդելներ, վահանակներ և մշտադիտարկվող որոշումներ։"], ["Python + pandas", "Թափանցիկ, կրկնվող վերլուծություն և վավերացում։"], ["Power Query / Alteryx", "Կրկնվող պատրաստում և գործընթացների ավտոմատացում։"]],
        capstoneTitle: "Ապացույցից որոշում վերլուծական ամփոփագիր", capstoneCopy: "Պատասխանեք իրական կազմակերպական հարցի՝ օգտագործելով փաստագրված տվյալներ, վերարտադրելի վերլուծություն, հստակ տեսողական ապացույց և առաջարկություն, որը բացահայտ հաղորդում է ենթադրությունները, անորոշությունն ու մշտադիտարկումը։", capstone: ["Որոշման հարց և տվյալների որակի գնահատում", "Վերարտադրելի վերլուծություն և տեսողական ապացույց", "Զգայունություն, այլընտրանքներ և սահմանափակումներ", "Առաջարկություն, գործողության շեմ և մշտադիտարկման պլան"]
      }
    },

    "entrepreneurs-startups": {
      en: {
        title: "AI for Entrepreneurs & Startups", audience: "For founders, early-stage teams, entrepreneurs, and business students", summary: "Use AI to validate problems, understand customers, design offers, prototype solutions, and operate a lean startup with speed and discipline.", outcome: "Build an evidence-backed venture concept and an AI-enabled founder workflow that moves from customer problem to tested prototype and next-step plan.",
        outcomes: [["Faster validation", "Research markets, structure interviews, and test assumptions before investing heavily."], ["Lean building", "Create positioning, prototypes, experiments, and investor-ready materials with human control."], ["Founder automation", "Automate research, lead handling, support, documentation, and operating updates."]],
        stateTitle: "AI is lowering the cost of learning and building.", stateCopy: "Small teams can now research, design, code, market, and support products with unprecedented leverage. The durable advantage is not output volume; it is faster evidence loops, customer understanding, proprietary context, and disciplined execution.", statePoints: ["AI-native products increasingly combine models, tools, memory, and human oversight.", "Rapid prototyping compresses build time but does not prove demand or retention.", "Founders must manage data rights, provider dependence, unit economics, safety, and defensibility."],
        sessions: [
          ["AI-native venture landscape", "Explore current startup models, identify valuable customer problems, and test whether AI is necessary and defensible.", ["Copilots, vertical AI, agents, and service-as-software", "Problem selection and market evidence", "Feasibility, data, cost, risk, and moat"], "Create a venture opportunity brief with falsifiable assumptions."],
          ["Founder daily operating system", "Use AI for interviews, customer synthesis, positioning, offers, content, outreach, and investor communication.", ["Interview guides and research synthesis", "Value proposition, pricing hypotheses, and landing copy", "Outreach, meeting preparation, and pitch narrative"], "Build a customer-evidence library and first offer package."],
          ["Prototype and automate", "Create a testable prototype and automate a small operating workflow without overbuilding.", ["No-code and AI-assisted prototyping", "Lead capture, onboarding, support, and founder reporting", "Testing, permissions, fallback, and cost control"], "Build a prototype plus one automation that supports acquisition or delivery."],
          ["Validate and pitch", "Run a structured test, interpret customer evidence, and present a credible next-stage plan.", ["Experiment design and learning metrics", "Business model, unit economics, and AI cost", "Risks, roadmap, and fundraising narrative"], "Pitch an evidence-backed AI venture with prototype, automation, and 30-day validation plan."]
        ],
        tools: [["ChatGPT / Claude", "Research, strategy, customer synthesis, and founder deliverables."], ["Perplexity", "Market, competitor, and technical landscape research."], ["Lovable / Replit", "Rapid working prototypes and lightweight applications."], ["Canva / Figma", "Product concepts, landing assets, and pitch materials."], ["Zapier / Make", "Lead, onboarding, operations, and notification workflows."], ["Airtable / Notion", "Customer evidence, experiments, CRM, and operating system."]],
        capstoneTitle: "Evidence-backed AI venture sprint", capstoneCopy: "Turn one problem into a coherent venture case with customer evidence, differentiated value proposition, testable prototype, lean automation, risk choices, and a focused validation roadmap.", capstone: ["Problem, customer evidence, and market map", "Value proposition and working prototype", "One founder workflow automation", "Business logic, risks, and 30-day validation plan"]
      },
      hy: {
        title: "ԱԲ-ը ձեռնարկատերերի և ստարտափների համար", audience: "Հիմնադիրների, վաղ փուլի թիմերի, ձեռնարկատերերի և բիզնեսի ուսանողների համար", summary: "Կիրառեք ԱԲ-ը խնդիրները վավերացնելու, հաճախորդներին հասկանալու, առաջարկներ նախագծելու, լուծումներ նախատիպելու և ստարտափը արագ ու կարգապահ վարելու համար։", outcome: "Ստեղծեք ապացույցներով հիմնավորված ձեռնարկատիրական գաղափար և հիմնադրի ԱԲ աշխատանքային համակարգ՝ հաճախորդի խնդրից մինչև փորձարկված նախատիպ ու հաջորդ քայլերի պլան։",
        outcomes: [["Ավելի արագ վավերացում", "Ուսումնասիրեք շուկաները, կառուցեք հարցազրույցներ և ստուգեք ենթադրությունները՝ նախքան մեծ ներդրումը։"], ["Խնայող կառուցում", "Մարդկային վերահսկմամբ ստեղծեք դիրքավորում, նախատիպեր, փորձեր և ներդրողների համար պատրաստ նյութեր։"], ["Հիմնադրի ավտոմատացում", "Ավտոմատացրեք հետազոտությունը, լիդերի մշակումը, աջակցությունը, փաստաթղթավորումն ու գործառնական թարմացումները։"]],
        stateTitle: "ԱԲ-ը նվազեցնում է սովորելու և կառուցելու արժեքը։", stateCopy: "Փոքր թիմերն այժմ կարող են աննախադեպ ուժով հետազոտել, նախագծել, կոդ գրել, շուկա հանել և աջակցել արտադրանքներին։ Կայուն առավելությունը արդյունքի ծավալը չէ, այլ ավելի արագ ապացույցների շրջանը, հաճախորդի ըմբռնումը, սեփական համատեքստն ու կարգապահ իրականացումը։", statePoints: ["ԱԲ-բնական արտադրանքներն ավելի հաճախ համատեղում են մոդելներ, գործիքներ, հիշողություն և մարդկային վերահսկում։", "Արագ նախատիպավորումը կրճատում է կառուցման ժամանակը, բայց չի ապացուցում պահանջարկը կամ պահպանումը։", "Հիմնադիրները պետք է կառավարեն տվյալների իրավունքները, մատակարարից կախվածությունը, միավորային տնտեսագիտությունը, անվտանգությունն ու պաշտպանելիությունը։"],
        sessions: [
          ["ԱԲ-բնական ձեռնարկությունների միջավայր", "Ուսումնասիրեք ստարտափների արդի մոդելները, բացահայտեք արժեքավոր հաճախորդային խնդիրներ և ստուգեք՝ արդյոք ԱԲ-ը անհրաժեշտ ու պաշտպանելի է։", ["Համաօգնականներ, ուղղահայաց ԱԲ, գործակալներ և ծառայություն որպես ծրագրային ապահովում", "Խնդրի ընտրություն և շուկայի ապացույց", "Իրագործելիություն, տվյալներ, արժեք, ռիսկ և պաշտպանելիություն"], "Կազմեք ձեռնարկատիրական հնարավորության ամփոփագիր՝ հերքելի ենթադրություններով։"],
          ["Հիմնադրի ամենօրյա աշխատանքային համակարգ", "ԱԲ-ը կիրառեք հարցազրույցների, հաճախորդների ամփոփման, դիրքավորման, առաջարկների, բովանդակության, կապի և ներդրողների հաղորդակցության մեջ։", ["Հարցազրույցների ուղեցույցներ և հետազոտության ամփոփում", "Արժեքային առաջարկ, գնագոյացման վարկածներ և էջի տեքստ", "Կապ, հանդիպման նախապատրաստում և ներկայացման պատմություն"], "Ստեղծեք հաճախորդային ապացույցների գրադարան և առաջին առաջարկի փաթեթ։"],
          ["Նախատիպ և ավտոմատացում", "Ստեղծեք փորձարկելի նախատիպ և ավտոմատացրեք փոքր գործառնական գործընթաց՝ առանց ավելորդ կառուցման։", ["Առանց կոդի և ԱԲ-ով աջակցվող նախատիպավորում", "Լիդերի հավաքում, մեկնարկ, աջակցություն և հիմնադրի հաշվետվություն", "Փորձարկում, թույլտվություններ, պահեստային ընթացք և ծախսի վերահսկում"], "Կառուցեք նախատիպ և մեկ ավտոմատացում, որն աջակցում է ձեռքբերմանը կամ ծառայության մատուցմանը։"],
          ["Վավերացում և ներկայացում", "Կատարեք կառուցվածքային փորձ, մեկնաբանեք հաճախորդային ապացույցները և ներկայացրեք հաջորդ փուլի իրատեսական պլան։", ["Փորձարկման նախագծում և ուսուցման չափիչներ", "Բիզնես մոդել, միավորային տնտեսագիտություն և ԱԲ ծախս", "Ռիսկեր, ճանապարհային քարտեզ և ներդրումային պատմություն"], "Ներկայացրեք ապացույցներով ԱԲ ձեռնարկություն՝ նախատիպով, ավտոմատացմամբ և 30-օրյա վավերացման պլանով։"]
        ],
        tools: [["ChatGPT / Claude", "Հետազոտություն, ռազմավարություն, հաճախորդների ամփոփում և հիմնադրի նյութեր։"], ["Perplexity", "Շուկայի, մրցակիցների և տեխնոլոգիական միջավայրի հետազոտություն։"], ["Lovable / Replit", "Արագ աշխատող նախատիպեր և թեթև հավելվածներ։"], ["Canva / Figma", "Արտադրանքի գաղափարներ, էջի նյութեր և ներկայացումներ։"], ["Zapier / Make", "Լիդերի, մեկնարկի, գործառույթների և ծանուցումների գործընթացներ։"], ["Airtable / Notion", "Հաճախորդային ապացույցներ, փորձեր, CRM և գործառնական համակարգ։"]],
        capstoneTitle: "Ապացույցներով ԱԲ ձեռնարկության արագ ծրագիր", capstoneCopy: "Մեկ խնդիրը վերածեք ամբողջական ձեռնարկատիրական հիմնավորման՝ հաճախորդային ապացույցներով, տարբերակված արժեքային առաջարկով, փորձարկելի նախատիպով, խնայող ավտոմատացմամբ, ռիսկերի ընտրությամբ և վավերացման հստակ ճանապարհային քարտեզով։", capstone: ["Խնդիր, հաճախորդային ապացույց և շուկայի քարտեզ", "Արժեքային առաջարկ և աշխատող նախատիպ", "Հիմնադրի մեկ աշխատանքային ավտոմատացում", "Բիզնես տրամաբանություն, ռիսկեր և 30-օրյա վավերացման պլան"]
      }
    },

    "hr-recruitment": {
      en: {
        title: "AI in HR & Recruitment", audience: "For HR professionals, recruiters, people leaders, and managers", summary: "Improve workforce planning, recruiting, onboarding, development, and employee service while protecting fairness, privacy, and human dignity.", outcome: "Build a human-reviewed talent workflow that improves one HR process and includes clear fairness, privacy, explainability, and escalation controls.",
        outcomes: [["Better talent work", "Create role profiles, structured interviews, onboarding, development, and employee communications."], ["Responsible insight", "Analyze people data and feedback without turning weak patterns into high-stakes judgments."], ["Safe automation", "Automate coordination and support tasks while reserving consequential decisions for accountable humans."]],
        stateTitle: "HR AI is powerful - and especially high stakes.", stateCopy: "Recruiting copilots, skills intelligence, employee-service assistants, and people analytics are advancing quickly. Because these systems affect opportunity and livelihoods, quality must include fairness, privacy, accessibility, explainability, and meaningful human review.", statePoints: ["Skills-based talent models are complementing traditional job and credential taxonomies.", "AI can reduce administrative load but may reproduce historical bias in data and process design.", "Automated employment decisions face growing legal, ethical, and reputational scrutiny."],
        sessions: [
          ["HR AI landscape and responsible boundaries", "Understand current HR applications and identify where AI may assist, where it requires review, and where it should not decide.", ["Recruiting, skills, learning, service, and analytics tools", "Bias, privacy, accessibility, and explainability", "High-impact decisions and human accountability"], "Complete a risk-and-value assessment for one HR use case."],
          ["Daily HR and recruiting workflows", "Improve job analysis, sourcing preparation, structured selection, onboarding, learning, and communication.", ["Job profiles and competency frameworks", "Interview guides, scorecards, and candidate communication", "Onboarding plans and manager toolkits"], "Build a structured, inclusive hiring or onboarding pack for one role."],
          ["HR automation and people analytics", "Design safe workflows for scheduling, FAQs, document routing, feedback synthesis, and workforce reporting.", ["Employee-service and knowledge assistants", "Survey and feedback analysis", "Data minimization, access controls, and escalation"], "Prototype a human-reviewed HR service or coordination automation."],
          ["Fairness review and implementation", "Test the workflow for bias, accessibility, privacy, error, and user trust, then present a responsible rollout plan.", ["Adverse-impact thinking and test cases", "Candidate and employee transparency", "Policy, governance, monitoring, and appeals"], "Present a talent workflow with safeguards, templates, measures, and implementation plan."]
        ],
        tools: [["ChatGPT / Claude", "Role analysis, structured content, communication, and policy drafts."], ["Microsoft Copilot / Gemini", "Everyday HR documents, meetings, and productivity workflows."], ["LinkedIn Recruiter AI", "Talent search and recruiting context with human validation."], ["Workday / SAP SuccessFactors AI", "Enterprise talent, skills, and employee-service workflows."], ["Power BI", "People analytics and monitored workforce reporting."], ["Power Automate / Zapier", "Scheduling, routing, reminders, and controlled handoffs."]],
        capstoneTitle: "Responsible AI talent workflow", capstoneCopy: "Redesign one recruiting, onboarding, development, or employee-service process and demonstrate improved quality or efficiency with explicit fairness, privacy, transparency, and human-review controls.", capstone: ["Current-state and future-state talent journey", "Working templates or automation prototype", "Fairness, privacy, accessibility, and escalation review", "Measures, policy note, and rollout plan"]
      },
      hy: {
        title: "ԱԲ-ը մարդկային ռեսուրսներում և հավաքագրման մեջ", audience: "ՄՌ մասնագետների, հավաքագրողների, մարդկանց ղեկավարների և կառավարիչների համար", summary: "Բարելավեք աշխատուժի պլանավորումը, հավաքագրումը, մեկնարկը, զարգացումն ու աշխատակիցների սպասարկումը՝ պաշտպանելով արդարությունը, գաղտնիությունն ու մարդկային արժանապատվությունը։", outcome: "Ստեղծեք մարդու կողմից ստուգվող տաղանդների գործընթաց, որը բարելավում է ՄՌ մեկ գործառույթ և ներառում արդարության, գաղտնիության, բացատրելիության ու սրման հստակ վերահսկումներ։",
        outcomes: [["Ավելի լավ տաղանդների աշխատանք", "Ստեղծեք դերերի նկարագրեր, կառուցվածքային հարցազրույցներ, մեկնարկ, զարգացում և աշխատակիցների հաղորդակցություն։"], ["Պատասխանատու պատկերացում", "Վերլուծեք մարդկանց տվյալներն ու արձագանքները՝ թույլ օրինաչափությունները չվերածելով բարձր ազդեցության դատողությունների։"], ["Անվտանգ ավտոմատացում", "Ավտոմատացրեք համակարգման և աջակցության աշխատանքները՝ նշանակալի որոշումները թողնելով պատասխանատու մարդկանց։"]],
        stateTitle: "ՄՌ ԱԲ-ը հզոր է և հատկապես բարձր ռիսկային։", stateCopy: "Հավաքագրման համաօգնականները, հմտությունների հետախուզությունը, աշխատակիցների սպասարկման օգնականներն ու մարդկանց վերլուծությունը արագ զարգանում են։ Քանի որ այս համակարգերը ազդում են հնարավորությունների և ապրուստի վրա, որակը պետք է ներառի արդարություն, գաղտնիություն, հասանելիություն, բացատրելիություն և իրական մարդկային ստուգում։", statePoints: ["Հմտությունների վրա հիմնված տաղանդների մոդելները լրացնում են աշխատանքի և վկայականների ավանդական դասակարգումները։", "ԱԲ-ը կարող է նվազեցնել վարչական ծանրաբեռնվածությունը, բայց վերարտադրել տվյալների ու գործընթացի պատմական կողմնակալությունը։", "Աշխատանքի ավտոմատ որոշումները ենթարկվում են աճող իրավական, էթիկական և հեղինակության վերահսկման։"],
        sessions: [
          ["ՄՌ ԱԲ միջավայր և պատասխանատու սահմաններ", "Հասկացեք ՄՌ արդի կիրառումները և որոշեք՝ որտեղ ԱԲ-ը կարող է օգնել, որտեղ է ստուգում պետք, և որտեղ այն չպետք է որոշի։", ["Հավաքագրման, հմտությունների, ուսուցման, սպասարկման և վերլուծության գործիքներ", "Կողմնակալություն, գաղտնիություն, հասանելիություն և բացատրելիություն", "Բարձր ազդեցության որոշումներ և մարդկային պատասխանատվություն"], "Կատարեք մեկ ՄՌ կիրառման ռիսկի և արժեքի գնահատում։"],
          ["ՄՌ և հավաքագրման ամենօրյա գործընթացներ", "Բարելավեք աշխատանքի վերլուծությունը, որոնման նախապատրաստումը, կառուցվածքային ընտրությունը, մեկնարկը, ուսուցումն ու հաղորդակցությունը։", ["Դերերի նկարագրեր և կարողությունների շրջանակներ", "Հարցազրույցների ուղեցույցներ, գնահատման քարտեր և թեկնածուի հաղորդակցություն", "Մեկնարկի պլաններ և ղեկավարների գործիքակազմ"], "Ստեղծեք մեկ դերի կառուցվածքային ու ներառական հավաքագրման կամ մեկնարկի փաթեթ։"],
          ["ՄՌ ավտոմատացում և մարդկանց վերլուծություն", "Նախագծեք անվտանգ գործընթացներ ժամանակացույցի, հաճախակի հարցերի, փաստաթղթերի ուղղորդման, արձագանքի ամփոփման և աշխատուժի հաշվետվության համար։", ["Աշխատակիցների սպասարկման և գիտելիքի օգնականներ", "Հարցումների և արձագանքների վերլուծություն", "Տվյալների նվազեցում, հասանելիության վերահսկում և սրում"], "Ստեղծեք մարդու կողմից ստուգվող ՄՌ սպասարկման կամ համակարգման ավտոմատացման նախատիպ։"],
          ["Արդարության ստուգում և ներդրում", "Փորձարկեք գործընթացը կողմնակալության, հասանելիության, գաղտնիության, սխալի և վստահության տեսանկյունից, ապա ներկայացրեք պատասխանատու ներդրման պլան։", ["Անբարենպաստ ազդեցության մտածողություն և թեստային դեպքեր", "Թեկնածուի ու աշխատակցի թափանցիկություն", "Քաղաքականություն, կառավարում, մշտադիտարկում և բողոքարկում"], "Ներկայացրեք պաշտպանիչ միջոցներով, ձևանմուշներով, չափիչներով և ներդրման պլանով տաղանդների գործընթաց։"]
        ],
        tools: [["ChatGPT / Claude", "Դերերի վերլուծություն, կառուցվածքային բովանդակություն, հաղորդակցություն և քաղաքականության սևագրեր։"], ["Microsoft Copilot / Gemini", "Ամենօրյա ՄՌ փաստաթղթեր, հանդիպումներ և արտադրողականության գործընթացներ։"], ["LinkedIn Recruiter AI", "Տաղանդների որոնում և հավաքագրման համատեքստ՝ մարդկային վավերացմամբ։"], ["Workday / SAP SuccessFactors AI", "Կազմակերպական տաղանդների, հմտությունների և աշխատակիցների սպասարկման գործընթացներ։"], ["Power BI", "Մարդկանց վերլուծություն և մշտադիտարկվող աշխատուժի հաշվետվություն։"], ["Power Automate / Zapier", "Ժամանակացույց, ուղղորդում, հիշեցումներ և վերահսկվող փոխանցումներ։"]],
        capstoneTitle: "Պատասխանատու ԱԲ տաղանդների գործընթաց", capstoneCopy: "Վերանախագծեք հավաքագրման, մեկնարկի, զարգացման կամ աշխատակիցների սպասարկման մեկ գործընթաց և ցուցադրեք որակի կամ արդյունավետության բարելավումը՝ արդարության, գաղտնիության, թափանցիկության և մարդկային ստուգման հստակ վերահսկումներով։", capstone: ["Տաղանդների ներկա և ապագա ճանապարհ", "Աշխատող ձևանմուշներ կամ ավտոմատացման նախատիպ", "Արդարության, գաղտնիության, հասանելիության և սրման ստուգում", "Չափիչներ, քաղաքականության նշում և ներդրման պլան"]
      }
    },

    "education-teaching": {
      en: {
        title: "AI in Education & Teaching", audience: "For teachers, lecturers, trainers, and academic leaders", summary: "Use AI to design learning, explanations, feedback, and inclusive support while protecting assessment validity, student agency, and academic integrity.", outcome: "Build a complete AI-supported learning unit with authentic assessment, transparent student guidance, efficient feedback, and clear human oversight.",
        outcomes: [["Stronger learning design", "Align objectives, activities, explanations, practice, and support around how learners develop understanding."], ["Authentic assessment", "Design evidence-rich tasks that preserve student thinking and make AI use transparent."], ["Teacher workflows", "Improve preparation, differentiation, feedback, administration, and resource creation responsibly."]],
        stateTitle: "Education is shifting from detection to redesign.", stateCopy: "Current advances include adaptive tutors, multimodal explanations, accessible content, learning analytics, and teacher copilots. The strongest educational response is not simply banning or detecting AI; it is redesigning learning and assessment around evidence, dialogue, process, and judgment.", statePoints: ["General-purpose models can tutor and explain, but may confidently teach errors or bypass productive struggle.", "Multimodal and accessibility features can widen participation when educators verify quality and representation.", "Assessment validity depends on knowing what evidence of learning the task actually produces."],
        sessions: [
          ["AI, learning, and the educator's role", "Understand current educational advances, limits, and evidence, then set a responsible classroom or institutional position.", ["Tutors, copilots, content generation, and analytics", "Learning science, productive struggle, and cognitive offloading", "Privacy, safeguarding, bias, accessibility, and academic integrity"], "Audit one existing course or lesson for high-value opportunities and learning risks."],
          ["Daily teaching workflows", "Use AI to plan, explain, differentiate, create resources, and provide feedback while keeping disciplinary expertise visible.", ["Outcome-aligned lesson and activity design", "Examples, explanations, practice, and differentiation", "Feedback rubrics, comment banks, and teacher review"], "Build an AI-supported lesson pack with differentiated resources and verification notes."],
          ["Automation and learner support", "Design a bounded assistant or workflow for FAQs, resource recommendation, formative practice, or course administration.", ["Knowledge-grounded course assistants", "Formative practice and feedback loops", "Escalation, data minimization, monitoring, and teacher control"], "Prototype a supervised learner-support assistant or teaching administration workflow."],
          ["Assessment redesign and course policy", "Create authentic assessment, student guidance, and an implementation plan aligned with learning outcomes.", ["Process evidence, oral defense, and authentic performance", "AI-use disclosure and student guidance", "Evaluation plan, staff development, and policy"], "Present an AI-supported learning unit with assessment, guidance, safeguards, and evaluation plan."]
        ],
        tools: [["ChatGPT / Claude", "Planning, explanation, practice, feedback, and reflective critique."], ["Microsoft Copilot / Gemini", "Teaching documents, presentations, communication, and collaboration."], ["NotebookLM", "Source-grounded study guides, explanations, and course knowledge."], ["Canva for Education", "Accessible learning materials and visual explanations."], ["Moodle / Canvas AI features", "Course workflows, support, analytics, and assessment integration."], ["MagicSchool / Khanmigo", "Education-specific planning and guided learning workflows."]],
        capstoneTitle: "AI-supported learning unit", capstoneCopy: "Redesign one real unit so AI strengthens - not replaces - learning. Align objectives, teaching activities, learner support, authentic assessment, transparency, safeguards, and evaluation.", capstone: ["Learning objectives and redesigned sequence", "Verified resources and supervised support workflow", "Authentic assessment and AI-use guidance", "Safeguarding, integrity, and evaluation plan"]
      },
      hy: {
        title: "ԱԲ-ը կրթության և դասավանդման մեջ", audience: "Ուսուցիչների, դասախոսների, վերապատրաստողների և ակադեմիական ղեկավարների համար", summary: "Կիրառեք ԱԲ-ը ուսուցման, բացատրությունների, հետադարձ կապի և ներառական աջակցության նախագծման մեջ՝ պաշտպանելով գնահատման վավերությունը, սովորողի ինքնուրույնությունն ու ակադեմիական ազնվությունը։", outcome: "Ստեղծեք ԱԲ-ով աջակցվող ամբողջական ուսումնական միավոր՝ իրական գնահատմամբ, սովորողի թափանցիկ ուղեցույցով, արդյունավետ հետադարձ կապով և հստակ մարդկային վերահսկմամբ։",
        outcomes: [["Ավելի ուժեղ ուսումնական նախագծում", "Համաձայնեցրեք նպատակները, գործողությունները, բացատրությունները, վարժությունն ու աջակցությունը սովորողի ըմբռնման ձևավորման հետ։"], ["Իրական գնահատում", "Նախագծեք ապացույցներով հարուստ առաջադրանքներ, որոնք պահպանում են սովորողի մտածողությունը և ԱԲ կիրառումը դարձնում թափանցիկ։"], ["Դասավանդողի գործընթացներ", "Պատասխանատու կերպով բարելավեք նախապատրաստումը, տարբերակումը, հետադարձ կապը, վարչարարությունն ու նյութերի ստեղծումը։"]],
        stateTitle: "Կրթությունը հայտնաբերումից անցնում է վերանախագծման։", stateCopy: "Արդի առաջընթացը ներառում է հարմարվող ուսուցիչներ, բազմամոդալ բացատրություններ, հասանելի բովանդակություն, ուսուցման վերլուծություն և դասավանդողի համաօգնականներ։ Ուժեղ կրթական պատասխանը միայն ԱԲ-ն արգելել կամ հայտնաբերելը չէ, այլ ուսուցումն ու գնահատումը վերանախագծելը՝ ապացույցի, երկխոսության, գործընթացի և դատողության շուրջ։", statePoints: ["Ընդհանուր մոդելները կարող են ուսուցանել ու բացատրել, բայց նաև վստահորեն սխալ սովորեցնել կամ շրջանցել արդյունավետ դժվարությունը։", "Բազմամոդալ և հասանելիության հնարավորությունները կարող են ընդլայնել մասնակցությունը, երբ դասավանդողը ստուգում է որակն ու ներկայացվածությունը։", "Գնահատման վավերությունը կախված է նրանից, թե առաջադրանքն իրականում ուսման ինչ ապացույց է ստեղծում։"],
        sessions: [
          ["ԱԲ, ուսուցում և դասավանդողի դեր", "Հասկացեք կրթության արդի առաջընթացը, սահմանափակումներն ու ապացույցները, ապա սահմանեք պատասխանատու լսարանային կամ հաստատության դիրքորոշում։", ["Ուսուցիչներ, համաօգնականներ, բովանդակության ստեղծում և վերլուծություն", "Ուսուցման գիտություն, արդյունավետ դժվարություն և ճանաչողական բեռնաթափում", "Գաղտնիություն, պաշտպանություն, կողմնակալություն, հասանելիություն և ակադեմիական ազնվություն"], "Ստուգեք մեկ գործող դասընթաց կամ դաս՝ բարձրարժեք հնարավորությունների և ուսման ռիսկերի համար։"],
          ["Դասավանդման ամենօրյա գործընթացներ", "ԱԲ-ը կիրառեք պլանավորման, բացատրության, տարբերակման, նյութերի ստեղծման և հետադարձ կապի մեջ՝ պահպանելով մասնագիտական գիտելիքի տեսանելիությունը։", ["Արդյունքներին համապատասխան դասի ու գործողությունների նախագծում", "Օրինակներ, բացատրություններ, վարժություն և տարբերակում", "Հետադարձ կապի չափանիշներ, մեկնաբանությունների բանկ և դասավանդողի ստուգում"], "Ստեղծեք ԱԲ-ով աջակցվող դասի փաթեթ՝ տարբերակված նյութերով և ստուգման նշումներով։"],
          ["Ավտոմատացում և սովորողի աջակցություն", "Նախագծեք սահմանափակված օգնական կամ գործընթաց՝ հաճախակի հարցերի, նյութերի առաջարկման, ձևավորող վարժության կամ դասընթացի վարչարարության համար։", ["Աղբյուրներով հիմնավորված դասընթացի օգնականներ", "Ձևավորող վարժություն և հետադարձ կապի շրջան", "Սրում, տվյալների նվազեցում, մշտադիտարկում և դասավանդողի վերահսկում"], "Ստեղծեք վերահսկվող սովորողի աջակցության օգնականի կամ դասավանդման վարչական գործընթացի նախատիպ։"],
          ["Գնահատման վերանախագծում և դասընթացի քաղաքականություն", "Ստեղծեք իրական գնահատում, սովորողի ուղեցույց և ուսումնական նպատակներին համապատասխան ներդրման պլան։", ["Գործընթացի ապացույց, բանավոր պաշտպանություն և իրական կատարում", "ԱԲ կիրառման բացահայտում և սովորողի ուղեցույց", "Գնահատման պլան, աշխատակազմի զարգացում և քաղաքականություն"], "Ներկայացրեք ԱԲ-ով աջակցվող ուսումնական միավոր՝ գնահատմամբ, ուղեցույցով, պաշտպանիչ միջոցներով և գնահատման պլանով։"]
        ],
        tools: [["ChatGPT / Claude", "Պլանավորում, բացատրություն, վարժություն, հետադարձ կապ և քննադատական անդրադարձ։"], ["Microsoft Copilot / Gemini", "Ուսումնական փաստաթղթեր, ներկայացումներ, հաղորդակցություն և համագործակցություն։"], ["NotebookLM", "Աղբյուրներով ուսումնական ուղեցույցներ, բացատրություններ և դասընթացի գիտելիք։"], ["Canva for Education", "Հասանելի ուսումնական նյութեր և տեսողական բացատրություններ։"], ["Moodle / Canvas AI", "Դասընթացի գործընթացներ, աջակցություն, վերլուծություն և գնահատման ինտեգրում։"], ["MagicSchool / Khanmigo", "Կրթությանը հատուկ պլանավորման և ուղղորդված ուսուցման գործընթացներ։"]],
        capstoneTitle: "ԱԲ-ով աջակցվող ուսումնական միավոր", capstoneCopy: "Վերանախագծեք մեկ իրական միավոր, որպեսզի ԱԲ-ը ուժեղացնի, ոչ թե փոխարինի ուսուցումը։ Համաձայնեցրեք նպատակները, դասավանդման գործողությունները, սովորողի աջակցությունը, իրական գնահատումը, թափանցիկությունը, պաշտպանիչ միջոցներն ու արդյունքների գնահատումը։", capstone: ["Ուսումնական նպատակներ և վերանախագծված հաջորդականություն", "Վավերացված նյութեր և վերահսկվող աջակցության գործընթաց", "Իրական գնահատում և ԱԲ կիրառման ուղեցույց", "Պաշտպանություն, ազնվություն և գնահատման պլան"]
      }
    }
  };

  const fallback = "business-management";
  const params = new URLSearchParams(window.location.search);
  const slug = courses[params.get("course")] ? params.get("course") : fallback;
  const languageSelect = document.getElementById("language");
  let language = localStorage.getItem("eua-ai-language") === "hy" ? "hy" : "en";
  const esc = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");

  function render() {
    const text = ui[language];
    const course = courses[slug][language];
    document.documentElement.lang = language;
    document.title = `${course.title} · ${text.brand}`;
    document.getElementById("meta-description").setAttribute("content", `${course.summary} ${text.meta}`);
    languageSelect.value = language;
    document.querySelectorAll("[data-copy]").forEach((element) => { if (text[element.dataset.copy]) element.innerHTML = text[element.dataset.copy]; });
    document.getElementById("course-title").textContent = course.title;
    document.getElementById("course-summary").textContent = course.summary;
    document.getElementById("course-audience").textContent = course.audience;
    document.getElementById("course-outcome").textContent = course.outcome;
    document.getElementById("course-facts").innerHTML = `<div><strong>2</strong><span>${text.weeks}</span></div><div><strong>4</strong><span>${text.sessions}</span></div><div><strong>8</strong><span>${text.hours}</span></div><div><strong>20</strong><span>${text.participants}</span></div>`;
    document.getElementById("outcome-grid").innerHTML = course.outcomes.map((item, index) => `<article class="outcome-card"><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join("");
    document.getElementById("state-title").textContent = course.stateTitle;
    document.getElementById("state-copy").textContent = course.stateCopy;
    document.getElementById("state-points").innerHTML = course.statePoints.map((point, index) => `<div class="state-point"><span>0${index + 1}</span><p>${esc(point)}</p></div>`).join("");
    document.getElementById("session-list").innerHTML = course.sessions.map((session, index) => {
      const week = index < 2 ? 1 : 2;
      const day = index % 2 + 1;
      const timing = text.weekDay.replace("{w}", week).replace("{d}", day);
      return `<article class="session-card"><div class="session-index">${text.session} 0${index + 1} · <strong>${timing}</strong></div><div><h3>${esc(session[0])}</h3><p class="session-focus">${esc(session[1])}</p></div><div><ul>${session[2].map((item) => `<li>${esc(item)}</li>`).join("")}</ul></div><div class="session-lab"><strong>${text.lab}</strong><span>${esc(session[3])}</span></div></article>`;
    }).join("");
    document.getElementById("tools-grid").innerHTML = course.tools.map((tool) => `<article class="tool-card"><strong>${esc(tool[0])}</strong><p>${esc(tool[1])}</p></article>`).join("");
    document.getElementById("capstone-title").textContent = course.capstoneTitle;
    document.getElementById("capstone-copy").textContent = course.capstoneCopy;
    document.getElementById("capstone-deliverables").innerHTML = course.capstone.map((item) => `<li>${esc(item)}</li>`).join("");
  }

  languageSelect.addEventListener("change", () => { language = languageSelect.value; localStorage.setItem("eua-ai-language", language); render(); });
  document.getElementById("year").textContent = new Date().getFullYear();
  render();

  const form = document.getElementById("inperson-form");
  const status = document.getElementById("form-status");
  form.addEventListener("submit", async (event) => {
    event.preventDefault();
    const text = ui[language];
    const data = Object.fromEntries(new FormData(form).entries());
    data.course_slug = slug;
    status.className = "form-status";
    status.textContent = text.saving;
    try {
      const response = await fetch("/api/in-person-interest", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) });
      if (!response.ok) throw new Error();
      form.reset();
      status.className = "form-status success";
      status.textContent = text.success;
    } catch (_error) {
      status.className = "form-status error";
      status.textContent = text.error;
    }
  });
})();
