(function () {
  "use strict";
  const tracks = {
    en: {
      students: { title: "AI for Students", copy: "Practical AI skills for stronger study, research, and creative work.", heading: "Make AI useful without losing your own thinking.", detail: "Learn to research, analyse, create, and communicate with academic integrity.", facts: [["6h", "video learning"], ["18", "lessons"], ["6", "module tests"], ["1", "portfolio project"]], modules: [["Study", "Plan, explain, practise, and review without outsourcing your thinking."], ["Research", "Find sources, verify claims, and document how AI contributed."], ["Create", "Develop presentations, data stories, and portfolio work."], ["Prepare", "Use AI for careers, interviews, and lifelong learning."]] },
      educators: { title: "AI for Educators", copy: "Thoughtful AI practice for teaching, assessment, and course design.", heading: "Teach with AI. Keep learning human.", detail: "Design better learning activities, feedback, and classroom policies with sound judgment.", facts: [["5h", "video learning"], ["15", "lessons"], ["5", "module tests"], ["1", "teaching plan"]], modules: [["Design", "Create aligned lessons, activities, and explanations."], ["Assess", "Build authentic assessment and responsible feedback workflows."], ["Guide", "Teach AI literacy, verification, and academic integrity."], ["Lead", "Develop a practical AI policy for your learning context."]] },
      government: { title: "AI for Public Sector & Governance", copy: "Responsible AI skills for public service professionals.", heading: "Use AI with public purpose and accountability.", detail: "Apply AI to everyday work while protecting data, fairness, transparency, and trust.", facts: [["4.5h", "video learning"], ["14", "lessons"], ["5", "module tests"], ["1", "applied scenario"]], modules: [["Understand", "Recognise useful public-sector applications and their limits."], ["Protect", "Handle data, privacy, security, and procurement responsibly."], ["Apply", "Improve analysis, communication, and service workflows."], ["Govern", "Document oversight, risk, transparency, and human accountability."]] }
    },
    hy: {
      students: { title: "ԱԲ ուսանողների համար", copy: "ԱԲ-ի գործնական հմտություններ՝ ավելի արդյունավետ ուսման, հետազոտության և ստեղծագործ աշխատանքի համար։", heading: "ԱԲ-ը դարձրեք օգտակար՝ չկորցնելով սեփական մտածողությունը։", detail: "Սովորեք հետազոտել, վերլուծել, ստեղծել և հաղորդակցվել՝ պահպանելով ակադեմիական ազնվությունը։", facts: [["6 ժ", "տեսանյութ"], ["18", "դաս"], ["6", "մոդուլային թեստ"], ["1", "պորտֆոլիոյի նախագիծ"]], modules: [["Ուսում", "Պլանավորեք, բացատրեք, փորձեք և վերանայեք՝ առանց ձեր մտածողությունը ԱԲ-ին հանձնելու։"], ["Հետազոտություն", "Գտեք աղբյուրներ, ստուգեք պնդումները և փաստագրեք ԱԲ-ի ներդրումը։"], ["Ստեղծում", "Մշակեք շնորհանդեսներ, տվյալների պատմություններ և պորտֆոլիոյի աշխատանքներ։"], ["Նախապատրաստում", "Կիրառեք ԱԲ-ը կարիերայի, հարցազրույցների և շարունակական ուսման համար։"]] },
      educators: { title: "ԱԲ դասավանդողների համար", copy: "ԱԲ-ի մտածված կիրառում դասավանդման, գնահատման և դասընթացների նախագծման մեջ։", heading: "Դասավանդեք ԱԲ-ի միջոցով։ Պահպանեք ուսուցման մարդկային էությունը։", detail: "Նախագծեք ավելի արդյունավետ ուսումնական աշխատանքներ, հետադարձ կապ և լսարանային կանոններ՝ հիմնվելով առողջ դատողության վրա։", facts: [["5 ժ", "տեսանյութ"], ["15", "դաս"], ["5", "մոդուլային թեստ"], ["1", "դասավանդման պլան"]], modules: [["Նախագծում", "Ստեղծեք նպատակներին համապատասխան դասեր, աշխատանքներ և բացատրություններ։"], ["Գնահատում", "Կառուցեք իրական գնահատման և պատասխանատու հետադարձ կապի գործընթացներ։"], ["Ուղղորդում", "Դասավանդեք ԱԲ գրագիտություն, ստուգում և ակադեմիական ազնվություն։"], ["Առաջնորդում", "Մշակեք ԱԲ-ի կիրառման գործնական քաղաքականություն ձեր կրթական միջավայրի համար։"]] },
      government: { title: "ԱԲ-ը հանրային կառավարման և պետական հատվածի համար", copy: "ԱԲ-ի պատասխանատու կիրառման հմտություններ հանրային ծառայության մասնագետների համար։", heading: "Կիրառեք ԱԲ-ը հանրային նպատակով և հաշվետվողականությամբ։", detail: "Կիրառեք ԱԲ-ը առօրյա աշխատանքում՝ պաշտպանելով տվյալները, արդարությունը, թափանցիկությունը և վստահությունը։", facts: [["4.5 ժ", "տեսանյութ"], ["14", "դաս"], ["5", "մոդուլային թեստ"], ["1", "կիրառական սցենար"]], modules: [["Հասկանալ", "Ճանաչեք հանրային ոլորտում օգտակար կիրառությունները և դրանց սահմանափակումները։"], ["Պաշտպանել", "Պատասխանատու կերպով կառավարեք տվյալները, գաղտնիությունը, անվտանգությունը և գնումները։"], ["Կիրառել", "Բարելավեք վերլուծությունը, հաղորդակցությունը և ծառայությունների գործընթացները։"], ["Կառավարել", "Փաստագրեք վերահսկողությունը, ռիսկը, թափանցիկությունը և մարդկային պատասխանատվությունը։"]] }
    }
  };
  const copy = {
    en: { brand: "EUA AI Academy", allCourses: "All courses", language: "Language", login: "Log in", back: "← All courses", comingSoon: "Coming soon", reminder: "Get a reminder <span aria-hidden=\"true\">↓</span>", firstToKnow: "Be first to know when enrollment opens", designed: "Designed for your role", assessment: "Assessment", assessmentTitle: "Practice, test, apply.", assessmentCopy: "Short module tests and an applied final project help turn learning into evidence.", courseReminders: "Course reminders", reachYou: "Tell us where to reach you.", privacy: "We will use these details only for updates about this course.", firstName: "First name *", lastName: "Last name *", email: "Email *", phone: "Phone <span>(optional)</span>", message: "Message <span>(optional)</span>", messagePlaceholder: "What would you most like to learn?", submit: "Remind me", saving: "Saving your reminder…", success: "You’re on the reminder list. We’ll be in touch.", error: "Could not save your reminder" },
    hy: { brand: "ՀԵՀ ԱԲ ակադեմիա", allCourses: "Բոլոր դասընթացները", language: "Լեզու", login: "Մուտք", back: "← Բոլոր դասընթացները", comingSoon: "Շուտով", reminder: "Ստանալ հիշեցում <span aria-hidden=\"true\">↓</span>", firstToKnow: "Առաջինը տեղեկացեք, երբ գրանցումը բացվի", designed: "Նախագծված է ձեր դերի համար", assessment: "Գնահատում", assessmentTitle: "Փորձեք, ստուգեք, կիրառեք։", assessmentCopy: "Կարճ մոդուլային թեստերը և եզրափակիչ կիրառական նախագիծը ուսումնառությունը վերածում են ապացույցի։", courseReminders: "Դասընթացի հիշեցումներ", reachYou: "Նշեք՝ ինչպես կապվել ձեզ հետ։", privacy: "Այս տվյալները կօգտագործենք միայն այս դասընթացի նորությունների համար։", firstName: "Անուն *", lastName: "Ազգանուն *", email: "Էլ. փոստ *", phone: "Հեռախոս <span>(ոչ պարտադիր)</span>", message: "Հաղորդագրություն <span>(ոչ պարտադիր)</span>", messagePlaceholder: "Ի՞նչ կցանկանայիք ամենից շատ սովորել։", submit: "Հիշեցնել ինձ", saving: "Պահպանում ենք ձեր հարցումը…", success: "Դուք հիշեցումների ցանկում եք։ Մենք կկապվենք ձեզ հետ։", error: "Չհաջողվեց պահպանել ձեր հարցումը" }
  };

  const requestedKey = new URLSearchParams(window.location.search).get("track");
  const key = tracks.en[requestedKey] ? requestedKey : "students";
  const select = document.getElementById("language");
  let language = localStorage.getItem("eua-ai-language") === "hy" ? "hy" : "en";

  function render() {
    const t = copy[language]; const track = tracks[language][key];
    document.documentElement.lang = language; select.value = language; document.title = `${track.title} · ${t.brand}`;
    document.querySelectorAll("[data-copy]").forEach((el) => { if (t[el.dataset.copy]) el.innerHTML = t[el.dataset.copy]; });
    document.querySelectorAll("[data-copy-placeholder]").forEach((el) => el.setAttribute("placeholder", t[el.dataset.copyPlaceholder]));
    document.getElementById("track-title").textContent = track.title; document.getElementById("track-copy").textContent = track.copy; document.getElementById("track-heading").textContent = track.heading; document.getElementById("track-detail").textContent = track.detail;
    document.getElementById("track-facts").innerHTML = track.facts.map(([value, label]) => `<div><strong>${value}</strong><span>${label}</span></div>`).join("");
    document.getElementById("track-curriculum").innerHTML = track.modules.map(([title, description], index) => `<div class="curriculum-row"><span>${String(index + 1).padStart(2, "0")}</span><h3>${title}</h3><p>${description}</p></div>`).join("");
  }
  select.addEventListener("change", () => { language = select.value; localStorage.setItem("eua-ai-language", language); render(); });
  render();

  const form = document.getElementById("reminder-form"); const status = document.getElementById("form-status");
  form.addEventListener("submit", async (event) => {
    event.preventDefault(); status.className = "form-status"; status.textContent = copy[language].saving;
    const data = Object.fromEntries(new FormData(form).entries()); data.course_slug = key;
    try { const response = await fetch("/api/course-interest", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || copy[language].error); form.reset(); status.className = "form-status success"; status.textContent = copy[language].success; }
    catch (_error) { status.className = "form-status error"; status.textContent = copy[language].error; }
  });
})();
